### ISSUE TITLE
resolv.conf might not be populated on startup

### ISSUE THREAD

**Issue by kristrev** [NEAT-project/neat#101]
We read resolv.conf when resolver is initialised and file is updated, but we have no guarantee that there are any DNS servers available when the request for resolving a domain is made. For example, NEWADDR might happen before resolver file is written to. As of now, we will use one of the public servers and the request will time out if for example they are blocked. However, it would make sense to add support no servers being available at resolve-time. We could for example add a separate resolv-timeout, or just handle this error internally in NEAT.

**Comment by irl** [comment]
It's worth noting that on some systems, resolv.conf may not even be a real file and may be a symlink to either a file provided by systemd-resolvd or network-manager. No guarantees are made that resolv.conf exists, this file is placed there as a courtesy to legacy applications.

**Comment by irl** [comment]
On systems using systemd-resolvd:

> A static file /usr/lib/systemd/resolv.conf is provided that lists the 127.0.0.53 DNS stub (see above) as only DNS server. This file may be symlinked from /etc/resolv.conf in order to connect all local clients that bypass local DNS APIs to systemd-resolved. This mode of operation is recommended.

This approach to collecting addresses of nameservers will fail on these platforms. (Debian stretch, coming up for release in the next year, is amongst these platforms.)
