### ISSUE TITLE
Rework resolver and add request callback

### ISSUE THREAD

**Issue by kristrev** [NEAT-project/neat#107]
The resolver currently does not support multiple flows or multiple requests. For example, one instance of the resolver is tied to one callback and one request. This does not work, what we need to is to implement a request queue and then process one request after the other. The function the application/libneat calls will be something like:

```
neat_resolve(ctx, flow, res_cb) //potentially remove ctx
```

This function will initialize the resolver (if not already initialized), add the request to a queue (list) and then start the request (if none is already in progress). After the request is done (in our internal callback), then we will start the second request (if any). If there are no requests available, we will mark that the resolver resources can be freed and free them in the after-callback. If a request is started before the after-callback, the request to free will be removed.

The structure of a request will be something like:

```
struct neat_resolver_request {
    struct neat_flow *flow;
    neat_resolver_handle_t *cb;
}
```

The change should not be very large, but will in particular need some reworking of the init function and where things are stored. An initial suggestion would be something like:

* Address monitoring should be kept in resolver.
* Server monitoring should be kept in resolver.
* Idle and timeout should be kept in resolver (they are the generic callbacks).
* Most of what is in getaddrinfo() will be private to one request.

**Comment by kristrev** [comment]
Considering supporting multiple flows depends on reworking the resolver, I will try to look at this next week.

**Comment by adventureloop** [comment]
Just so our discussion is captured:

- Resolver creation will be moved into `neat_init_ctx`
- Requests will only go through the `neat_resolve` call.
- The resolver will endevour to use resources in the most sensible way, resolver will be cleaned up in `neat_free_ctx`

The memory leaking is going to continue until we can refactor all allocations into calls in this style.

**Comment by kristrev** [comment]
After going through the code, I see that resolver itself never requires the flow. Instead of storing a flow in the neat_resolver_request, it would make more sense to have a void pointer. I think I also want to keep the domain name/service in this struct, so that we can keep this decoupling and for example PVD does not need to fake a flow.

**Comment by kristrev** [comment]
Another thing that will probably be changed is that resolver will return much less information. Initial goal was that it should work similar to getaddrinfo() and return one struct per protocol-combination. This does not make sense, HE can create this already. DNS should only be concerned address family. Port can be stored in for example flow (which can be stored in the data pointer of structure).

**Comment by kristrev** [comment]
I am also considering storing all handles, pairs, etc. in the neat_resolver_request struct. After scratching my head a bit, I can't find any big reason not to. They are all "private" to one DNS lookup. The only thing that might speak against it, at least in my opinion, is that spacing requests out in time might be trickier. However, I think the advantages outweighs this. For example, we can have true async, parallel DNS. No queue or anything.

**Comment by kristrev** [comment]
Done.
