### ISSUE TITLE
Multiple flows within one NEAT context

### ISSUE THREAD

**Issue by oystedal** [NEAT-project/neat#108]
Ensure that the implementation is able to support multiple flows in the same NEAT context, e.g. that a server is able to handle multiple concurrent clients. This includes being able to support concurrent execution of `neat_open` against itself and against `neat_accept`.

**Comment by kristrev** [comment]
Tom, Felix and me had some discussions about how to make this work during the day. We have some ideas, all starting with reworking the resolver.

**Comment by oystedal** [comment]
Is there anything else blocking this issue?

The resolver has been reworked, and we support multiple incoming connections. The only thing I don't think has been tested is a client with multiple flows, but I don't think this should be an issue.

I vote for closing this. Anyone else?
