### ISSUE TITLE
Allocation of buffers is clumsy 

### ISSUE THREAD

**Issue by adventureloop** [NEAT-project/neat#109]
Right now it is quite clumsy to allocated the message send buffer, it needs to know the number of flows. This will makes it hard to to map to a single alloc single free model for resources.

 `allocate_send_buffers(flow);`

I suggest adding a new call to allow reallocation of stream buffers and allocating a default of 1 stream for each flow in `neat_new_flow`

    neat_flow *neat_new_flow(neat_ctx *mgr)
    {
        ...
         // default establish 1 stream
         allocate_send_buffers(flow, 1); 
        ...
    }

`reallocate_send_buffers(flow, 10);`

**Comment by oystedal** [comment]
I have no objections to this. Feel free to assign it to me unless you feel like doing it yourself :)

**Comment by adventureloop** [comment]
@oystedal I won't get to it until next week, feel free to drop me off the ticket if you start the work.
