### ISSUE TITLE
PvD integration into Policy Manager

### ISSUE THREAD

**Issue by NTag** [NEAT-project/neat#110]
# Report of breakout session about Policy Manager in Oslo
### About PvD

A Provisioning Domain (PvD) is all the information you can attach to a source address (like the throughput, the accessible prefixes, the address of the DNS server...). One way of getting it (which is implemented in NEAT) is by using DNS ([draft-stenberg-mif-mpvd-dns-00](https://tools.ietf.org/html/draft-stenberg-mif-mpvd-dns-00)).
1. You take your prefix, you compute the reverse record of it, and you prefix it with `_pvd.`:
   `2001:db8:bad:a55::100/64 -> _pvd.5.5.a.0.d.a.b.0.8.b.d.0.1.0.0.2.ip6.arpa`
2. You perform a DNS query for **PTR** records:

```
    dns_query('_pvd.5.5.a.0.d.a.b.0.8.b.d.0.1.0.0.2.ip6.arpa', TYPE_PTR)
        -> students1.school.edu
```
1. You perform a DNS query for **TXT** records matching the name you get:

```
    dns_query('students1.school.edu', TYPE_TXT)
        -> 6=2001:db8:bad:a55::/64
        -> z=school.edu,school.org
        -> bw=50000
```
1. This answer says that, using the source address `2001:db8:bad:a55::100`:
   - you can reach the prefix `2001:db8:bad:a55::/64`;
   - you can resolve and reach the name `*.school.edu` and`*.school.org`;
   - the maximum throughput is 50 Mb/s.

Here is some information you can get:
- the IP of the DNS servers;
- the accessible IPv4 prefixes;
- the accessible IPv6 prefixes;
- the searchable names;
- the maximum thoughput;
- the minimum latency;
- the address of the HTTP proxy server (if any);
- the monetary cost...
## CIB

PvDs are here to **complete the CIB** about the sources, but it is not the only way.

We can also use DHCP (which can give you the DNS servers to use or the searchable domains), Router Discovery Protocol (which can give you the accessible IPv6 prefixes)...

Actually, the CIB can provide a lot of information about your sources, destinations and connections.
## When is the PM called?

Here is a typical workflow for a request with a name. It is just a case among others but it is a starting point.

![neat pm](https://cloud.githubusercontent.com/assets/906276/16459975/730dd4c8-3e25-11e6-9844-e06dba26fcc8.png)
## Next
- Other cases? (when a destination IP is specified, when a source IP is specified)
- Writing more concrete examples
- Defining the design of the Policy Manager and its interaction with the resolver
- How NEAT could request an explicit choice from the user?

**Comment by evyncke** [comment]
thanks
