### ISSUE TITLE
IPC options for PM interface

### ISSUE THREAD

**Issue by bozakov** [NEAT-project/neat#111]
We need to converge on a mechanism for interfacing the policy manager, i.e., to transfer JSON encoded application requests and the candidate list from/to the NEAT logic. A first list of possible options:

+ TCP sockets
+ Unix Domain Sockets
+ POSIX IPC
+ POSIX shared memory
+ netlink
+ zeromq

Are there any preferences?

**Comment by oystedal** [comment]
I think a UNIX socket is the best option.

**Comment by karlgrin** [comment]
I would definitely rule out the four lower-most alternatives, and since we probably do not envision PM to run on a separate machine, I would also opt for UNIX sockets.

**Comment by bozakov** [comment]
I agree with the UNIX sockets option. If there are no objections, I'll close the issue.

**Comment by mcmanus** [comment]
I have no objection.. fwiw for those considering Windows support they would
need an alternative.. going w local host tcp would avoid that

**Comment by bozakov** [comment]
Good point about Windows. I guess the two options are similar enough to easily handle this in a windows port ..(btw. is any one currently working on/testing this?)
