### ISSUE TITLE
Improve Happy Eyeballs

### ISSUE THREAD

**Issue by tuexen** [NEAT-project/neat#126]
Currently HE only takes into account whether the connection/association setup is successful, but not if the actual connection works. This happens, for example, with HTTP/TCP/IPv4 and HTTP/TCP/IPv6 due to MTU issues. NEAT should track this and, if possible, take this into account.

**Comment by karlgrin** [comment]
@tuexen @oystedal  Could this issue be closed?

**Comment by oystedal** [comment]
I have not experienced any further issues, so this may be closed in my opinion.
