### ISSUE TITLE
Test cases for listening

### ISSUE THREAD

**Issue by oystedal** [NEAT-project/neat#128]
Test listening, accepting and receiving on multiple sockets.

**Comment by oystedal** [comment]
@weinrank: Can you have a look at the test for server_echo in https://github.com/NEAT-project/neat/tree/oystedal/listen_test/tests? `test_echo.c` implements the actual test, while `run_echo_test.sh` demonstrates how it could be called by the buildbot. You don't have to use this file directly, it is probably safer to make a copy of it.

The purpose is not really to test `server_echo`, but to test NEAT's ability to accept incoming connections on the different protocols and to receive and send a tiny amount of data on each.

Let me know if there's anything else I need to change before this can be implemented in the buildbot.

**Comment by weinrank** [comment]
Hey Øystein,

this looks good to me - I'm happy about every test i can add to the BB system and testing the server side was on my agenda too. 👍  

Im currently playing around with your code to automize the test(s) including valgrind support...

**Comment by oystedal** [comment]
@weinrank: Any progress on this?

**Comment by tuexen** [comment]
@oystedal: weinrank is on vacation this week.

**Comment by weinrank** [comment]
@oystedal Hey, sorry for the delay.

I made a separate branch to play with your code and made some changes - not perfect but a first step:

https://github.com/NEAT-project/neat/tree/weinrank/listen_test/tests

## test_echo
* test script(s) is/are copied to the build directory.
This is done by cmake, but only(!) when running cmake in a clean build directory for the first time and not when there is already a cmake cache. 
Have it in mind when modifying the script - took some time for me to recognize... ;)

* test_echo.sh supports adding a prefix for the server and client execution.
So starting it with `test_echo.sh valgrind` will result in valgrind usage.

 ## general buildbot testing
I'm not happy with the current buildbot testing scenario.
Every test has its own buildbot step and the configuration file as well as the output becomes more and more messy. Most of the steps are tests and i think this will increase.

My idea is to have a single script which runs all the desired tests.
So every developer can add its own tests and this keeps the buildbot configuration handy.

What do you think?

**Comment by oystedal** [comment]
Sounds good to me.

I think it might be good to split the tests a little, e.g. one test suite execution without valgrind followed by the same test suite executed with valgrind, as separate buildbot steps. This makes it easy to identify whether the issue is related to functionality or just a memory error. I think this should be easy to manage if all tests support adding a prefix like you've done.

There were some security concerns raised during the Oslo plenary regarding having a test suite/config that everyone could edit, considering that these machines are connected directly to the Internet, as far as I understood. Not sure how we can address this. The addresses and domains to test against might have to be part of the buildbot config, which is reasonable IMO.

**Comment by weinrank** [comment]
Yes, splitting it into steps for "regular" tests and valgrind is the plan.

We still have these concerns and we'll put the buidlslaves in a private network.
