### ISSUE TITLE
bad assert() in he_resolve_cb()

### ISSUE THREAD

**Issue by bagder** [NEAT-project/neat#135]
The `assert(results->lh_first)` in the function `he_resolve_cb`on [line 121 in neat_he.c](https://github.com/NEAT-project/neat/blob/master/neat_he.c#L121) triggers in a test of mine.

That callback is occasionally called from `neat_resolver_timeout_shared` on [line 322 in neat_resolver.c](https://github.com/NEAT-project/neat/blob/master/neat_resolver.c#L322) with a NULL pointer in the first argument, that ends up in the `results` pointer in `he_resolve_cb`.

So the assert() seems to dereference that NULL pointer, but it also seems to use assert() for a case that is quite likely to occur and to me it looks like there should be a plain `if` check instead?

**Comment by karlgrin** [comment]
I don't think it is the asserts that are the culprits. Instead, it seems 
to me that there should be 'returns' following lines 114 and 116.
Since we are curently reworking HE in NEAT, the 'he_resolve_cb' function 
will soon be replaced (see branch 'oystedal/pm_interface')
so this issue should hopefully be resolved once this work is concluded.

Daniel Stenberg wrote:

**Comment by bagder** [comment]
Yeah, I've not checked the logic around this close enough to say what the culprit is or what change I would suggest. I just get stuck on that assert() in my tests and that assert() looks wrong so I wanted to file it here.

**Comment by oystedal** [comment]
I remember this issue now. If you run NEAT using valgrind or similar, the existing DNS timeout is not sufficient. Temporarily increasing the timeouts at https://github.com/NEAT-project/neat/blob/master/neat_resolver.h#L15 may possibly resolve this issue. We could do this permanently for DEBUG builds.

In general, I would say that most asserts in the NEAT code are for development only, and should eventually be removed.

**Comment by bagder** [comment]
I'm single-stepping code with gdb so yes, basically any timeouts will be too short =)
