### ISSUE TITLE
Policy Manager execution during tests

### ISSUE THREAD

**Issue by oystedal** [NEAT-project/neat#138]
The code on the oystedal/pm_interface branch is materializing, and at some point it will be necessary to run the policy manager as part of some test.

Some useful information:
- The policy manager requires at least Python 3.0, if not higher (do you know exactly, @bozakov?)
- NEAT will by default look for a UNIX socket in `$HOME/.neat/neat_pm_socket`.
- This path can be overridden by defining the environment variable `NEAT_PM_SOCKET`.
- The PM can be executed as follows: `python neatpmd.py [--cib <path to cib dir>] [--pib <path to pib dir>] [--sock <path to unix socket>]`
- NEAT is able to run without the PM, although the connection candidates are generated far less intelligently in this case.

@weinrank: Feel free to reassign this once it's possible for others to write the test ;) Just make sure we have Python 3.5 on (all/some of) the buildslaves, and that it's possible to execute tests based on the points above.

**Comment by weinrank** [comment]
Python 3.5 is installed on Ubuntu and all FreeBSD buildslaves.
