### ISSUE TITLE
master branch compile failure

### ISSUE THREAD

**Issue by weinrank** [NEAT-project/neat#140]
Hey all,

the master branch doesn't compile on some conditions, see buildbots.
This is related to the PR #137 by Daniel.

`set_primary_dest_resolve_cb` should now return an error code.
There are SCTP/USRSCTP related codepaths in this function where only `return` is called, e.g. [here](https://github.com/NEAT-project/neat/blob/master/neat_core.c#L1547)

This is why the buildbots complain.
I have an open PR  #139 which fixes this.

@tuexen @bagder 
I'm not sure if the function should return `NEAT_ERROR_IO` or silently ignore.
Can you check this?

Greetings

**Comment by bagder** [comment]
Ah, time to add a travis job or something that run on pull-requests so things like this are caught earlier. I obviously don't build this code path locally so I didn't see this. PR coming up with a fix shortly!

**Comment by weinrank** [comment]
Travis? We have buildbots! 😎 😄 
They start 30s after you commited something to *any* branch.

http://buildbot.nplab.de:28010/waterfall
You can filter by branch like this
http://buildbot.nplab.de:28010/waterfall?branch=your_branch_name

Have a look at my PR, is it fine for you?
https://github.com/NEAT-project/neat/pull/139

**Comment by bagder** [comment]
Can the buildbots feedback on pull-requests when they cause build failures? That's the feature I'm talking about. Then a PR that causes a build-break wouldn't get merged in the first place. But I'll make sure to watch the buildbots from now on!

**Comment by weinrank** [comment]
Yeah, i already tried to use the Github-API but it's a bit more tricky than i thought initially... it's on my agenda! ;)

**Comment by tuexen** [comment]
By looking at the kernel code:
* Why is the SCTP_ASSOCINFO getsockopt() call made? The assoc_id is ignored for 1-to-1 style sockets, which we are using in NEAT.
* Why is the code #ifdef'ed for Linux? It should also run on FreeBSD. and even on all platforms supporting kernel SCTP.

**Comment by bagder** [comment]
I figure the code should rather be #ifdef'ed on something that was checked by the cmake script...

**Comment by tuexen** [comment]
You can either use HAVE_NETINET_SCTP_H, which is checked by the cmake script and assume that all SCTP implementations support SCTP_PRIMARY_ADDR, which is true as far as I know, or you could check, if SCTP_PRIMARY_ADDR is defined.
But get rid of the SCTP_ASSOCINFO code, which is wrong there, and don't restrict the code to Linux.

**Comment by oystedal** [comment]
The use of `SCTP_ASSOCINFO` in this case is (yet again) my fault. I'm not sure why I restricted it to Linux in the first place, but if it looks correct, I'll remove it.

The buildbots agree on #139 and nobody has objected to it, so I'll merge that one and then fix this function.
