### ISSUE TITLE
Negative delta times in the log function

### ISSUE THREAD

**Issue by bagder** [NEAT-project/neat#144]
I see this happen repeatedly. The call to `neat_log_init` from `neat_init_ctx` resets the time stamp to which subsequent log entries are calculated against but that first function call makes a log entry itself and that ends up with a negative value:

`[  -1.1000000][INF] neat_log_init - NEAT_LOG_LEVEL : default`

It appears as if the intent is that it should rather output a zero time there.

I presume negative delta time happens because the global struct `tv_init` isn't marked volatile so it may in fact not have been properly written to at the time `neat_log` is called. Or something like that.

**Comment by weinrank** [comment]
I will check this.

**Comment by weinrank** [comment]
See #146 

The problem was an incorrect calculation:
If both `timevals` have the same `tv_usec`, the calculation was wrong.
