### ISSUE TITLE
func.neat_set_property.md is out of date

### ISSUE THREAD

**Issue by bagder** [NEAT-project/neat#162]
commit 91dafe90ce6 completely changed `neat_set_property` but the documentation is still showing the old way of working... Can I suggest that we don't change public APIs without also updating the corresponding API?

**Comment by oystedal** [comment]
I'll update the documentation.

I have a bit of a backlog documentation-wise, I'm planning on taking care of that in the second half of the next month.

**Comment by bagder** [comment]
But why merge code that introduces the new functionality if we can't figure out how to use it?

**Comment by oystedal** [comment]
We now have documentation on ReadTheDocs, which largely supersedes the documentation in the `doc/` directory. Documentation for `neat_set_property` is here: http://neat.readthedocs.io/en/latest/neat_set_property.html and documentation for properties in general is here: http://neat.readthedocs.io/en/latest/properties.html.
