### ISSUE TITLE
How to close a flow?!

### ISSUE THREAD

**Issue by weinrank** [NEAT-project/neat#164]
Hey,

I'm stuck: how to close properly **close a flow** and when should we **call neat_free_flow()**?

https://github.com/NEAT-project/neat/blob/weinrank/nghttp2/examples/client_http_get.c
Is this fine? I can't find any notes in the docs?

**Comment by oystedal** [comment]
I think the way it's written in `client_http_get.c` is reasonable. Is there anything wrong with that approach?

**Comment by adventureloop** [comment]
I think neat_free_flow ends with you stuck in an infinite loop,  [peer](https://github.com/NEAT-project/neat/blob/master/examples/peer.c#L528) calls to neat_close. Semantically neat_close makes the most sense to me.

**Comment by weinrank** [comment]
@adventureloop 

So, to close a neat flow: just call `neat_close()`? 
What's about `neat_free_flow()`? Not necessary when using `neat_close()`?

It's about semantics ... if tried several ways, all have bugs. ;)

**Comment by weinrank** [comment]
To be more detailed:

I'm thinking about the semantics for closing a flow in general:
* Is it necessary to delete/unset all the handler before calling `neat_close()` or is it done automatically?
* Will `neat_close()` call `on_closed()` when finished for all protocols?
* Is it necessary to call `neat_free_flow()` when calling `neat_close()`?
* How to use `neat_free_flow()` in general?

Think about two two concurrent flows and you want to close one explicitly.

**Comment by adventureloop** [comment]
I think there are nesting issues between `neat_close()` and `neat_free_flow()`, one ends up calling the other, if you pick wrong you get stuck in a loop. This part of the stack is a mess right now. 

I think we want:
* `on_close()` can be generated by the application or by neat (apps wants to stop, tcp connection dies)
* `neat_close()` is how the app signals to neat it wants to stop
* `on_close()` is where the app tidies up the flow state, the flows lifetime has ended at this point
 - the flow is dead, so the app removes the handles.
 - a one shot app can stop the event loop here
 - app calls `neat_free_flow()` it is done with the flow

The `peer` test script runs through full application life cycle for the sender side, look there for an example of an app that works through this(or it did work in Oslo).

**Comment by adventureloop** [comment]
There are two ways an application can get a flow:
* `neat_new_flow()`
* `on_connected` after a `neat_accept`

Who should free the memory associated with the flow?

**Comment by oystedal** [comment]
Good point.

I imagine `neat_free_flow` could be needed for cases where you create a flow, but don't open (or listen to) it. Thus, it would make sense to explicitly disallow the use of `neat_free_flow` on a flow that has been opened. For opened flows, they would all be freed at some point after the execution of the `on_close` callback.

**Comment by weinrank** [comment]
@oystedal Sounds good!

We should improve the docs and make some flow / state charts before implementing... ;)

**Comment by weinrank** [comment]
@oystedal 

When freeing the flow within `on_close()` the `neat_free_candidates()` function is called. 
That function also frees the `handle`. I've seen this mostly when using IP-literals.
https://github.com/NEAT-project/neat/blob/weinrank/nghttp2/neat_core.c#L394

This handle is used/accessed when the `walk_cb()` is called at the end.
I've commented this line out, to avoid segfault and only have valgrind complaining about lost memory. 

Can you have a look at it?

BTW: Any objections to merge the code to the master branch?

**Comment by oystedal** [comment]
I'll have a look at it.

What code do you want to merge? Commenting out that line?

**Comment by weinrank** [comment]
Thanks!

#165 that one. ;)

**Comment by oystedal** [comment]
Turns out to be a rather silly mistake on my part. https://github.com/NEAT-project/neat/commit/aa59af4a27a5aabe9ed3d71fcef18eaacddb36d1 should fix this. Feel free to cherry-pick it into your branch.

I'll have a look at the pull request now.

**Comment by weinrank** [comment]
lgtm - merged it into mine...

**Comment by oystedal** [comment]
I've changed my mind a little about this. I'm going to axe `neat_free_flow` from the public API, so that there is only one true way of closing/deallocating a flow, `neat_close`, regardless of the state of the flow. `neat_free_flow` will continue to exist internally.
