### ISSUE TITLE
Multiple sockets

### ISSUE THREAD

**Issue by weinrank** [NEAT-project/neat#166]
Hey, me again! :)

I've seen an odd behavior: If I establish a connection between two neat enabled peers (`client`) and (`echo_server`) where TCP and SCTP is available, `on_connected()` is called twice on the  `echo_server` (once for TCP, once for SCTP). On the server side log you see that two sockets are closed. The `client` only has a single flow.

Attached a logfile from `client` and `echo_server`.
[client.txt](https://github.com/NEAT-project/neat/files/527518/client.txt)
[server.txt](https://github.com/NEAT-project/neat/files/527519/server.txt)

**Comment by oystedal** [comment]
I can't quite see the behavior you're describing based on the log output. I can only see one `on_connected()` in the client log.

The reason why you're seeing two `on_connected()` in the server log is because the server is listening to two sockets (SCTP and TCP, as per the default settings). The HE code currently has a 10ms delay between trying each candidate. If your RTT is >10ms (approximately), then two connection attempts will be made. However, communication will only be done on the first socket to connect, which in this case should be the one using SCTP.

Optimizing the choice of delay between candidates based on RTT (if known) has been discussed in emails between UiO, UoK and EMC.

**Comment by tuexen** [comment]
I think on the client side the HE implementation hides the fact that you use multiple transport connections for a single neat flow. On the server side, no such mechanism does exist. We actually don't assume that the server side is neat-enabled. The question might be how to have a HE server side implementation hiding the HE testing from the server application.

**Comment by weinrank** [comment]
@tuexen 
That explains the behavior.

@oystedal 
Sorry, my explanation was badly written, sorry for that.

Here's the part of the server's log file I'm talking about:

```
[   3.937622][DBG] do_accept
[   3.937627][DBG] neat_new_flow
[   3.937635][DBG] Creating new SCTP socket - in-/out-streams offered : 1988
[   3.937639][DBG] neat_accept_via_kernel
[   3.937650][DBG] io_connected
[   3.937658][INF] io_connected - SCTP - number of streams: 10
[   3.937669][INF] Connected: SCTP/IPv4 - 10 streams
on_connected - available streams : 10
[   3.937722][DBG] neat_set_operations
[   3.937727][DBG] updatePollHandle
[   3.937732][DBG] uvpollable_cb
[   3.937736][DBG] updatePollHandle
[   3.937742][DBG] do_accept - SCTP - number of streams: 1207
[   3.947880][DBG] uvpollable_cb
[   3.947890][DBG] do_accept
[   3.947896][DBG] neat_new_flow
[   3.947907][DBG] neat_accept_via_kernel
[   3.947921][DBG] io_connected
[   3.947928][INF] Connected: TCP/IPv4 - 1 streams
on_connected - available streams : 1
```

The `on_connected` without a timestamp is the output from the application, the server sees two streams.

Felix

**Comment by tuexen** [comment]
@weinrank BTW, why do you use such a strange number of streams:
```
Creating new SCTP socket - in-/out-streams offered : 1988
```
Is this a bug or intentional?

**Comment by weinrank** [comment]
;) intentional!

**Comment by oystedal** [comment]
One "solution" to this could be to let the application decide if the `on_connected` callback should be deferred. Most application layer protocols are initiated by the client sending a message to the server, so we could hide HE by not calling `on_connected` immediately upon a client connecting, but instead call `on_connected` before the first `on_readable` call.
