### ISSUE TITLE
Support address update in resolver

### ISSUE THREAD

**Issue by kristrev** [NEAT-project/neat#17]
We need to handle address update messages in the resolver, so that we can remove pairs with a source address that is deprecated. Function will be very similar to deladdr.

**Comment by weinrank** [comment]
@kristrev can we close this issue?

**Comment by kristrev** [comment]
Will have a look at this and the other issue during the telco. Right now I
am on holiday :)

Kristian

**Comment by naeemk** [comment]
@kristrev ping :)

**Comment by kristrev** [comment]
This is a non-issue and can be closed. We update the liftetime of addresses and the resolver will not use deprecated addresses. I see that we should probably keep track of when we last update timer so we can compute the current timer value, but that is not something I am going to do now.
