### ISSUE TITLE
`flow->socket` is not set up in the `neat_accept` path

### ISSUE THREAD

**Issue by adventureloop** [NEAT-project/neat#179]

**Comment by oystedal** [comment]
Nor is it meant to be, according to my design at least.

When an accepting flow opens sockets to listen on, it uses the `listen_sockets` list instead, in order to support listening to multiple sockets. An accepting flow never uses the `flow->socket`, this is as intended from my side.

If you're talking about the `accept()`-ed flow however, i.e. the one forked off from the listening socket, then that is certainly a bug.

**Comment by adventureloop** [comment]
Okay then, the accept()-ed flow is not set up.

**Comment by oystedal** [comment]
Then I have no idea what's wrong, or how to fix it. The buildbot doesn't complain when testing `server_echo`, so something seems to be working, at least.

How do I reproduce this error, and what is expected to happen instead?

**Comment by adventureloop** [comment]
Test with a udp server, socket matching doesn't work because the struct is junk. 

	[Switching to Thread 804215000 (LWP 101286/neat-streamer)]

	Breakpoint 2, do_accept (ctx=0x80450d600, flow=0x80428a480, listen_socket=0x80428a780)
		at /usr/home/tom/code/neat-streamer/neat/neat_core.c:1491
	(gdb) p *listen_socket
	$6 = {flow = 0x80428a480, fd = 16, family = 2 '\002', type = 2, stack = 1, port = 2779096485, 
	  dst_address = 0xa5a5a5a5a5a5a5a5 <Error reading address 0xa5a5a5a5a5a5a5a5: Bad address>, dst_sockaddr = {
		ss_len = 165 '¥', ss_family = 165 '¥', __ss_pad1 = 0x80428a7aa '¥' <repeats 200 times>..., 
		__ss_align = -6510615555426900571, __ss_pad2 = 0x80428a7b8 '¥' <repeats 200 times>...}, 
	  dst_len = 2779096485, 
	  src_address = 0xa5a5a5a5a5a5a5a5 <Error reading address 0xa5a5a5a5a5a5a5a5: Bad address>, src_sockaddr = {
		ss_len = 165 '¥', ss_family = 165 '¥', __ss_pad1 = 0x80428a83a '¥' <repeats 130 times>, "\020\002\0339", 
		__ss_align = -6510615555426900571, __ss_pad2 = 0x80428a848 '¥' <repeats 116 times>, "\020\002\0339"}, 
	  src_len = 2779096485, srcAddr = {sa_len = 16 '\020', sa_family = 2 '\002', sa_data = 0x80428a8be "\0339"}, 
	  dstAddr = {sa_len = 16 '\020', sa_family = 2 '\002', sa_data = 0x80428a8ce "\203U\213\205004"}, 
	  handle = 0x80423f840, next = {tqe_next = 0x0, tqe_prev = 0x80428a488}}

**Comment by oystedal** [comment]
Ok, take a look at https://github.com/NEAT-project/neat/commit/97a288a02dae9d3aaea26fb4042d22471e8c5554.

For flows accepting UDP connections, the `src_sockaddr` field of the listening UDP socket is the sockaddr that is received from the resolver when the accepting flow is created. The `dst_sockaddr` field of the listening socket is used for temporary storage of the peer address when a new UDP flow connects. The connecting UDP flow copies these two sockaddrs into its own `neat_pollable_socket` struct during `do_accept`.

Let me know if this commit fixes this issue. If not, then I am slightly confused.

**Comment by adventureloop** [comment]
It looks great, but the addresses I am getting are junk data. I am trying to figure out why now.

**Comment by oystedal** [comment]
Sounds strange. I'll do a quick test here and see if I get the same result.

**Comment by oystedal** [comment]
Indeed I am getting weird addresses as well.

**Comment by oystedal** [comment]
I was printing it incorrectly.

The following shows the addresses correctly for me, in neat_core.c at around line 1003.

```c
            char addrbuf[INET6_ADDRSTRLEN];
            char localaddrbuf[INET6_ADDRSTRLEN];
            memset(addrbuf, 0, sizeof(addrbuf));
            memset(localaddrbuf, 0, sizeof(localaddrbuf));
            inet_ntop(socket->family, (void*)&((struct sockaddr_in*)(&peerAddr))->sin_addr, addrbuf, sizeof(addrbuf));
            inet_ntop(socket->family, (void*)&((struct sockaddr_in*)(&socket->src_address))->sin_addr, localaddrbuf, sizeof(localaddrbuf));
```
