### ISSUE TITLE
server_daytime: -v option is ignored

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#185]
Trying to reduce the verbosity of server_daytime's output, I tried:
/server_daytime -v 0
/server_daytime -v 1
/server_daytime -v 2
There seems to be no change in the output verbosity. In any case, there it a lot of debugging information printed on the screen.

**Comment by dreibh** [comment]
"-v" is also ignored for "client" (and probably for other examples as well).

**Comment by weinrank** [comment]
Will check that.

**Comment by weinrank** [comment]
There are two different log mechanisms, one for the examples and one for neat itself.

The verbosity of the examples is controlled by the `-v` parameter while the neat-internal logging mechanism is (currently) controlled by two environment variables:
`NEAT_LOG_LEVEL` and `NEAT_LOG_FILE`

I've written a documentation about it but I don't find it in the current one.
