### ISSUE TITLE
client: infinite loop when trying to query daytime service

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#186]
How to reproduce:
./server_daytime
In separate shell:
./client -v 2 localhost 8080

Result:
Infinite loop of:
...
[   3.291762][DBG] updatePollHandle
[   3.291773][DBG] uvpollable_cb
[   3.291819][DBG] io_readable
[   3.291828][DBG] updatePollHandle
[   3.291840][DBG] uvpollable_cb
[   3.291850][DBG] io_readable
[   3.291895][DBG] updatePollHandle
[   3.291907][DBG] uvpollable_cb
[   3.291917][DBG] io_readable
[   3.291926][DBG] updatePollHandle
[   3.291935][DBG] uvpollable_cb
[   3.291969][DBG] io_readable
[   3.291978][DBG] updatePollHandle
[   3.292012][DBG] uvpollable_cb
[   3.292024][DBG] io_readable
...

**Comment by dreibh** [comment]
When aborting "client" with SIGINT, the daytime_server terminates with this:

[   3.756803][DBG] neat_run_event_cb
[   4.681689][DBG] uvpollable_cb
[   4.681708][DBG] ERROR: bad file descriptor
[   4.681718][DBG] Socket layer errno: 104 (Connection reset by peer)
[   4.681722][DBG] neat_notify_aborted
[   4.681724][ERR] Unspecified internal error when polling socket
[   4.681726][DBG] neat_io_error

It is probably not intended to terminate the server here?

**Comment by weinrank** [comment]
I will check it. 

OS?

**Comment by dreibh** [comment]
Hi,

Onsdag 23. november 2016 04.17.01 skrev Felix Weinrank:
> I will check it. 
> 
> OS? 

Linux (Ubuntu 16.04).

-- 
Best regards / Mit freundlichen Grüßen / Med vennlig hilsen

=======================================================================
 Thomas Dreibholz

 Simula Research Laboratory
 Simula Innovation AS, Network Systems Group
 Visiting address: Martin Linges vei 17, 1364 Fornebu, Norway
 Mailing address:  P.O.Box 134, 1325 Lysaker, Norway
-----------------------------------------------------------------------
 E-Mail:     dreibh@simula.no
 Homepage:   http://simula.no/people/dreibh
=======================================================================

**Comment by oystedal** [comment]
I'm unable to reproduce any part of this issue on my system, which is Arch Linux running a Linux 4.8.10 kernel with the ck patches. I don't have a machine running ubuntu readily available. 

@weinrank: Did you test this, and if so, what was your result?

@dreibh: Do you get the same result if you specify `127.0.0.1` instead of `localhost`? Also, the entire log from the client is of interest. This could potentially help narrow down the issue. Just write it to a file and cut it at the point where it starts repeating itself.

**Comment by weinrank** [comment]
@oystedal I can't reproduce the problem.
