### ISSUE TITLE
client_http_get/client_https_get: core dump

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#187]
How to reproduce:
client_http_get www.nntb.no
(also: client_https_get www.nntb.no)

Result:
...
HTTP/1.1 301 Moved Permanently
Date: Wed, 23 Nov 2016 09:49:11 GMT
Server: Apache
Location: https://www.nntb.no/
Content-Length: 228
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.nntb.no/">here</a>.</p>
</body></html>
[   1.038835][DBG] updatePollHandle
[   1.038848][DBG] uvpollable_cb
[   1.038859][DBG] io_readable
on_readable - reading from flow
[   1.038872][DBG] neat_read
[   1.038883][DBG] neat_read_from_lower_layer
[   1.038894][DBG] neat_read_from_lower_layer 0
[   1.038908][DBG] neat_read_from_lower_layer 0
on_readable - neat_read() got 0 bytes - connection closed
on_close - flow closed OK!
[   1.038930][DBG] neat_set_operations
[   1.038942][DBG] updatePollHandle
on_close - active flows left : 0
on_close - stopping event loop
[   1.038966][DBG] neat_stop_event_loop
[   1.038981][DBG] updatePollHandle
[   1.038999][DBG] neat_free_ctx
[   1.039011][DBG] neat_remove_event_cb
[   1.039022][INF] neat_remove_event_cb - Removed callback for type 0
[   1.039032][DBG] neat_remove_event_cb
[   1.039041][INF] neat_remove_event_cb - Removed callback for type 2
[   1.039066][DBG] neat_free_flow
[   1.039077][DBG] neat_free_candidate
[   1.039088][DBG] neat_free_candidate: Handle used by flow, flow should release it
[   1.039097][DBG] neat_free_candidate
[   1.039123][DBG] neat_free_candidate: Release candidate after closing
client_http_get: src/unix/core.c:168: uv_close: Assertion `0' failed.
Avbrutt (SIGABRT) (kjerne lagret i fil)

Stack trace:
#0  0x00007f3edfd77c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: Fila eller mappa finnes ikke.
(gdb) bt
#0  0x00007f3edfd77c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f3edfd7b028 in __GI_abort () at abort.c:89
#2  0x00007f3edfd70bf6 in __assert_fail_base (fmt=0x7f3edfec13b8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7f3edfb39a4c "0", file=file@entry=0x7f3edfb38520 "src/unix/core.c", line=line@entry=168, 
    function=function@entry=0x7f3edfb38797 <__PRETTY_FUNCTION__.9664> "uv_close") at assert.c:92
#3  0x00007f3edfd70ca2 in __GI___assert_fail (assertion=assertion@entry=0x7f3edfb39a4c "0", file=file@entry=0x7f3edfb38520 "src/unix/core.c", line=line@entry=168, 
    function=function@entry=0x7f3edfb38797 <__PRETTY_FUNCTION__.9664> "uv_close") at assert.c:101
#4  0x00007f3edfb2774f in uv_close (handle=0x1f11500, close_cb=<optimised out>) at src/unix/core.c:168
#5  0x00007f3ee010cfa3 in neat_free_candidate (candidate=0x1f0d4a0) at /home/dreibh/src/neat/neat_core.c:413
#6  0x00007f3ee010d03e in neat_free_candidates (candidates=0x1f0cfa0) at /home/dreibh/src/neat/neat_core.c:435
#7  0x00007f3ee010d2fa in neat_free_flow (flow=0x1e199b0) at /home/dreibh/src/neat/neat_core.c:515
#8  0x00007f3ee010c9bc in neat_free_ctx (nc=0x1e12010) at /home/dreibh/src/neat/neat_core.c:255
#9  0x0000000000401abb in main (argc=2, argv=0x7ffe2d130848) at /home/dreibh/src/neat/examples/client_http_get.c:209
(gdb) 
#0  0x00007f3edfd77c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f3edfd7b028 in __GI_abort () at abort.c:89
#2  0x00007f3edfd70bf6 in __assert_fail_base (fmt=0x7f3edfec13b8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7f3edfb39a4c "0", file=file@entry=0x7f3edfb38520 "src/unix/core.c", line=line@entry=168, 
    function=function@entry=0x7f3edfb38797 <__PRETTY_FUNCTION__.9664> "uv_close") at assert.c:92
#3  0x00007f3edfd70ca2 in __GI___assert_fail (assertion=assertion@entry=0x7f3edfb39a4c "0", file=file@entry=0x7f3edfb38520 "src/unix/core.c", line=line@entry=168, 
    function=function@entry=0x7f3edfb38797 <__PRETTY_FUNCTION__.9664> "uv_close") at assert.c:101
#4  0x00007f3edfb2774f in uv_close (handle=0x1f11500, close_cb=<optimised out>) at src/unix/core.c:168
#5  0x00007f3ee010cfa3 in neat_free_candidate (candidate=0x1f0d4a0) at /home/dreibh/src/neat/neat_core.c:413
#6  0x00007f3ee010d03e in neat_free_candidates (candidates=0x1f0cfa0) at /home/dreibh/src/neat/neat_core.c:435
#7  0x00007f3ee010d2fa in neat_free_flow (flow=0x1e199b0) at /home/dreibh/src/neat/neat_core.c:515
#8  0x00007f3ee010c9bc in neat_free_ctx (nc=0x1e12010) at /home/dreibh/src/neat/neat_core.c:255
#9  0x0000000000401abb in main (argc=2, argv=0x7ffe2d130848) at /home/dreibh/src/neat/examples/client_http_get.c:209

**Comment by oystedal** [comment]
Yikes, looked at the wrong issue for the number to put in the commit message.

**Comment by oystedal** [comment]
Ok, I think I have narrowed this down to be caused by attempting to close unopened handles. Please give b1f6fcb817593278bf4738e3bbc29cb17b6f2b18 a test and see if this fixes the issue.

**Comment by dreibh** [comment]
Yes, b1f6fcb is working.
