### ISSUE TITLE
Naming inconsistencies for the examples

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#189]
examples/README.md mentions neat_http_get, but the program is called client_http_get.

Suggestion:
Use neat_http_get, neat_client, neat_server_*, etc.. This makes the purpose of the program clear.

When submitting the package to Debian for review, such naming will very likely be required, in order to distinguish the NEAT clients and servers from various other clients and servers.

**Comment by weinrank** [comment]
+1
