### ISSUE TITLE
client_https_get does not use HTTPS

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#190]
client_https_get just uses HTTP, not HTTPS:
client_https_get www.nntb.no

The result is an error message from the web server, complaining about plain HTTP on the TLS-enabled server port 443. (GitHub file upload does not work. I can provide a pcap trace, if needed.)

**Comment by oystedal** [comment]
This is likely a mishap when moving from the old property system using bitmasks to the new properties using JSON. I thought I updated and tested this, but I'll have a look at this anyway.

TODO:
- Ensure that client_https_get actually asks for security with precedence == 2
- Ensure that security is installed for flows where this property is present

@bozakov: Can we make the PM generate a candidate with security and a candidate without security if security is specified with precedence == 1? I realize that this is the case for other properties as well, so we might want to specify some sort of ordering for this expansion, if that makes sense.

**Comment by bozakov** [comment]
I could do that, but do we really want to have this expansion done inside the PM? Lets say we have _n_ optional (precedence==1) boolean properties, would we have to generate ~2^_n_ candidates? Or are you suggesting to do that only for security? If HE looks at the property anyway, can't it check if its optional or not?

**Comment by oystedal** [comment]
You're right @bozakov. We can actually do this directly in HE instead by queuing a candidate with the desirable properties followed by a candidate with all the desired properties removed (at least as a starting point). Quite slow of me to not think of this.

**Comment by karlgrin** [comment]
@oystedal Is this something that involves me, or do you intend to do it yourself?

**Comment by oystedal** [comment]
@karlgrin Up to you. I have a pretty clear idea of how to implement it, so I figured I might as well do it. If you want to take care of it, feel free to do so.

**Comment by karlgrin** [comment]
@oystedal By all means go ahead. However, to me it would make sense to accept my pull request first so that the HE-PM communication goes into master.

**Comment by abrunstrom** [comment]
Sorry to jump in, but should this functionality really go into the HE. 
Isn't the ranking of the candidates with some desirable properties not 
available a policy decision?

**Comment by oystedal** [comment]
I'm closing this issue since the main problem brought up in this issue has been resolved.

**Comment by bozakov** [comment]
@abrunstrom Not sure if understand your comment correctly: the PM _will_ rank the candidates taking all app properties and known CIB information into account. So, as a result of some request, the top ranked candidate may contain the property "security" which for some reason the user specified as optional (ignoring for now that IMO ”optional" security is a bit of an oxymoron) - this property could also have been expanded by a policy profile to something more specific like use_TLS.

Assuming that the PM does not know wether the destination supports TLS yet (eg. new server, or system has just booted), what more do you propose the PM to do? In my opinion this can only be properly handled by the component actually responsible for instantiating the feature - performing the TLS handshake in this case. If this fails, and the property was _not_ mandatory the component should ignore that failure without terminating the TCP connection.
