### ISSUE TITLE
SCTP extra 20 bytes in raw socket

### ISSUE THREAD

**Issue by mangis-emc** [NEAT-project/neat#191]
In order to minimise code changes in legacy application, I'm trying the approach of initiating the connection using NEAT and then, inside the `on_connected` callback, extract the raw socket descriptor, stop NEAT loop and pass the raw socket descriptor back to the legacy application logic.
It works with TCP, but with SCTP I always find 20 bytes in the client in the raw socket descriptor after the connection is established. Is it a chunk of ancillary data in SCTP? Using `neat_read` these bytes seem to be consumed or ignored.
To reproduce it, I added a modified minimal_client example in my branch here: https://github.com/NEAT-project/neat/blob/mangis/sctp/examples/minimal_client.c. I added a function that reads the raw socket inside any callback, even if it doesn't make sense. If you pair it with `server_echo`, inside `on_connected` you can see the 20 bytes.

**Comment by mangis-emc** [comment]
The 20 bytes have always this shape:
`01 80 00 00 14 00 00 00 00 00 00 00 01 00 01 00 29 01 00 00`
with the 17th incrementing by 2 at each run. Maybe on of our SCTP expert can say what it is by heart...

**Comment by tuexen** [comment]
Are you using a kernel stack (which OS?) or the userland stack?

**Comment by mangis-emc** [comment]
Kernel stack in Ubuntu 16.04.1

**Comment by tuexen** [comment]
That is an SCTP_ASSOC_CHANGE notification. See [RFC 6458](https://tools.ietf.org/html/rfc6458#section-6.1.1) for details. They are enabled in `neat_sctp_init_events()`.

Please note that you can't assume that you can get an fd for a neat flow. In case of a userland SCTP stack, there is not fd for a particular SCTP association.

**Comment by mangis-emc** [comment]
Thank you, that was quick! As I know very little about SCTP, isn't this notification part of the connection establishment? I see that it comes from the stack itself and not from the remote endpoint (that also explains why I couldn't find those bytes in any packet recorded by running wireshark in parallel), but when does it get read by NEAT?

You're right about the socket descriptor assumption, it's a first tentative to get the most without reimplementing legacy applications using the callback approach. With TCP I found the socket descriptor empty and ready to use after `on_connected`, so I blindly tried the same with SCTP assuming to find an empty socket again.

**Comment by tuexen** [comment]
When the stack inserts a notification in the socket receive buffer, the socket becomes readable.
It is then handled in https://github.com/NEAT-project/neat/blob/master/neat_core.c#L1125.

Please note that finding the fd not readable in `on_connected()` isn't guaranteed by anything. It is just about the application layer protocol and timing. Think running against a daytime server and having some delay in calling `on_connected()`...
