### ISSUE TITLE
HE should stop attempting new connections when one works

### ISSUE THREAD

**Issue by mangis-emc** [NEAT-project/neat#192]
As far as I've seen, when a connection works and there's no event to be processed by the main loop, HE keeps on trying to establish connections using the other candidates left in the queue.
HE should cancel any subsequent connection attempts once something has successfully connected.

And to check that the connection works there's a related issue: #126

**Comment by karlgrin** [comment]
@mangis-emc HE continues all of them so that it is able to cache connection results. The idea is that the next time cached results could be use and thus no extra connection attempts need to be carried out.

**Comment by mangis-emc** [comment]
@karlgrin are you saying that HE tries to connect to all the candidates to check if they work and it close them immediately after to cache results? Or does it keep them alive to reuse them later?

**Comment by karlgrin** [comment]
@mangis-emc You're correct in your observation: HE tries to connect to all the candidates to check if they work, cache the result, and close the connection.

**Comment by karlgrin** [comment]
@mangis-emc @oystedal Could this issue be closed?

**Comment by oystedal** [comment]
I would say it can be closed since this functionality is intended.

**Comment by mwelzl** [comment]
oh, is this the connection-cashing thing i asked about? sounds like it...
