### ISSUE TITLE
How to deal with desired properties in PM and HE

### ISSUE THREAD

**Issue by oystedal** [NEAT-project/neat#193]
Background: Off-topic discussion in #190.

My suggestion in #190 is not viable, as @abrunstrom pointed out, since this should be a policy decision. My new proposal is to treat this problem analogously to a binary search.

When the PM encounters a candidate C with any number of desirable properties, it generates exactly two candidates, C0 and C1. If there is no CIB information available, then C0 is equal to C and C1 is equal to C with all desired properties removed. C0 has a higher priority (lower number) than C1. The information from these connection attempts are cached in the CIB. 

On a subsequent connection attempt, the PM uses information stored in the CIB to determine which desirable properties to test. Assuming, C0 did not succeed from the previous iteration, two new candidates C2 and C3 are generated. C2 is equal to C with half of the desired properties removed. C3 is equal to C1, that is, equal to C with all desirable properties removed. The PM can whitelist properties/values from connection attempts that succeeded, and blacklist properties/values that occur repeatedly in failed connections. This way, over time, the connection will be established using a candidate with only the desired properties that result in a successful connection.

This can also be generalized to generate more than two candidates in each iteration, which could also be a policy decision.

**Comment by bozakov** [comment]
@oystedal I think your proposal is quite interesting. However I'm also afraid that we would introduce a fair bit of new complexity, while we still haven't fully looked at and understood many real use cases. My suggestion is to defer this for now. Right now, lets assume that HE ignores all optional properties, so the PM will try to set as many properties to mandatory as possible using policies and profiles. After we have run through a couple of use cases, we can revisit the property handling.

**Comment by oystedal** [comment]
Indeed, I don't see any point in rushing this feature.

**Comment by naeemk** [comment]
@bozakov: Can we say that the way the current policy system works (e.g. with priorities, scoring system in the candidate list) addresses this issue?

**Comment by bozakov** [comment]
@naeemk While I can think of scenarios which would require this feature, AFAIK it hasn't been needed in real world examples. We can close for now and re-open at some point in the future if it becomes necessary again.
