### ISSUE TITLE
OpenSSL 1.1.0+ build failures

### ISSUE THREAD

**Issue by bagder** [NEAT-project/neat#194]
I built neat from git master just now on Debian Unstable which now has OpenSSL 1.1.0c by default. It causes the build failures below that can be repaired with a patch similar to 
[0001-neat_security-fix-build-with-OpenSSL-1.1.0.patch](https://github.com/NEAT-project/neat/files/612728/0001-neat_security-fix-build-with-OpenSSL-1.1.0.patch.txt)

~~~
[  1%] Building C object CMakeFiles/neat.dir/neat_security.c.o
/home/daniel/src/neat/neat_security.c: In function ‘neat_security_install’:
/home/daniel/src/neat/neat_security.c:357:13: error: ‘TLSv1_2_client_method’ is deprecated [-Werror=deprecated-declarations]
             private->ctx = SSL_CTX_new(TLSv1_2_client_method());
             ^~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /home/daniel/src/neat/neat_security.h:7,
                 from /home/daniel/src/neat/neat_internal.h:10,
                 from /home/daniel/src/neat/neat_security.c:11:
/usr/include/openssl/ssl.h:1610:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void)) /* TLSv1.2 */
 ^
/home/daniel/src/neat/neat_security.c:361:13: error: ‘TLSv1_2_server_method’ is deprecated [-Werror=deprecated-declarations]
             private->ctx = SSL_CTX_new(TLSv1_2_server_method());
             ^~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /home/daniel/src/neat/neat_security.h:7,
                 from /home/daniel/src/neat/neat_internal.h:10,
                 from /home/daniel/src/neat/neat_security.c:11:
/usr/include/openssl/ssl.h:1609:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void)) /* TLSv1.2 */
 ^
/home/daniel/src/neat/neat_security.c: In function ‘neat_security_close’:
/home/daniel/src/neat/neat_security.c:433:5: error: ‘ERR_remove_state’ is deprecated [-Werror=deprecated-declarations]
     ERR_remove_state(0);
     ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/crypto.h:32:0,
                 from /usr/include/openssl/bio.h:20,
                 from /usr/include/openssl/err.h:21,
                 from /home/daniel/src/neat/neat_security.h:5,
                 from /home/daniel/src/neat/neat_internal.h:10,
                 from /home/daniel/src/neat/neat_security.c:11:
/usr/include/openssl/err.h:247:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
cc1: all warnings being treated as errors
CMakeFiles/neat.dir/build.make:330: recipe for target 'CMakeFiles/neat.dir/neat_security.c.o' failed
~~~

**Comment by oystedal** [comment]
Thanks for the heads up. The patch looks good to me.

**Comment by bagder** [comment]
I forgot to mention that detail, but when doing version number #ifdef checking with openssl a little extra fiddling is required if we want to retain ability to build with libressl as they have another numbering. The patch adapts to that.

**Comment by oystedal** [comment]
I have no issues with keeping that bit there, but it might seem strange to some when we don't officially support libressl (or do we?).

**Comment by adventureloop** [comment]
Does libressl support dtls? A quick grep of the man page doesn't give any results.

**Comment by bagder** [comment]
I don't have a strong opinion either way. In the curl project we support all three openssl forks because they're still similar enough so that it is possible and I took inspiration for the patch from there.

**Comment by tuexen** [comment]
Since I think we should support (D)TLS for all transports where it makes sense: SCTP, TCP, UDP (I think DTLS/UDPLite doesn't make sense). OpenSSL supports all of these. I'm fine with adding other SSL libraries, but we will have to deal with the case that not all of them support all protocols.
This means we might end up with using multiple ssl implementations at the same time or we add the missing support to the SSL libraries and get things merged upstream.

Taking into account that we don't support (D)TLS for all protocol choices yet, I would vote for completing OpenSSL support before adding the complexity of dealing with multiple ssl libraries (assuming that we don't want to implement DTLS support in one of the libraries).

**Comment by adventureloop** [comment]
I would like to avoid the ifdef spaghetti we would end up with when we have multiple tls implementations with differing support for features. I would like to keep the security critical parts of neat as simple as possible.

**Comment by bagder** [comment]
I filed #198 without the libressl thing
