### ISSUE TITLE
HE cache entries should contain all candidate properties received from PM

### ISSUE THREAD

**Issue by bozakov** [NEAT-project/neat#197]
CIB cache entries generated by HE for the policy manager should contain _all_ candidate properties as received from the PM to ensure that future requests match. Currently this is a fixed set of properties. 

@karlgrin @oystedal Could you please have a look at this?

**Comment by oystedal** [comment]
`candidate->properties` should contain all properties received from the PM for that particular candidate. In other words, maybe this is what should be sent back to the PM?

**Comment by bozakov** [comment]
That looks right, and this would have to be inserted under the properties attribute in the JSON structure defined for `result_array` on line 1349

**Comment by karlgrin** [comment]
Ok. I'll look into it.

**Comment by karlgrin** [comment]
@oystedal @bozakov  Could this issue be closed?

**Comment by bozakov** [comment]
One additional request @karlgrin: could we remove the `interface` property from the properties array. This is exception is needed because the `interface` property is contained in the match array.

**Comment by karlgrin** [comment]
Ok. I will check this; Maybe not this week, but probably the next.
