### ISSUE TITLE
Access to neat_internal.h by examples

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#201]
3 examples access NEAT internals from  #include <neat_internal.h>:

$ grep neat_internal *.c
client.c:#include <neat_internal.h>
peer.c:#include <neat_internal.h>
server_echo.c:#include <neat_internal.h>

It is probably not intended for a user to access these internal structures? If some accesses are intended, proper public API functions need to be defined.

**Comment by weinrank** [comment]
It is not and was planned as a temporary solution.

I'm currently working on the examples and will delete the include.

**Comment by weinrank** [comment]
The `client` needs access to the UV event loop to read from stdin.

Any suggestions how to realize? We could expose the `neat_ctx` structure or (preferred by me) offer a function which returns the loop pointer...

**Comment by oystedal** [comment]
Giving unconditional access to the `neat_ctx` structure is a guaranteed way to introduce errors when applications start hacking away on it.

I'd say that exposing the loop pointer in the API is sufficient. It's also possible to use `NEAT_RUN_NOWAIT` and poll both the backend fd and stdin from the main function of `client`.
