### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by weinrank** [NEAT-project/neat#203]
Hey,

I added a test case where the `client_http_get` connects to a host which doesn't have listening service on that port. 

In that case, `on_error()` is called which calls `neat_close()`.
This leads to failed assertion:
http://buildbot.nplab.de:28010/builders/freebsd-head/builds/194/steps/testing/logs/stdio

**Comment by oystedal** [comment]
Looking into this now.

**Comment by oystedal** [comment]
Please give https://github.com/NEAT-project/neat/commit/27a23f6c596b336b7b96e5a82853c233f00b5cae a try.

**Comment by weinrank** [comment]
lgtm! 👍

**Comment by oystedal** [comment]
:tada:
