### ISSUE TITLE
SCTP_MULTIHOMING: reason for variant without multi-homing support?

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#206]
Is there a reason to create a NEAT version without multi-homing support, by not defining SCTP_MULTIHOMING? If SCTP is available, it makes sense to always support multi-homing as well. This avoids to maintain and debug different versions of the NEAT library.

**Comment by tuexen** [comment]
It should not be a compile time switch, but a runtime switch. Something you can request as a user. If the user request some way of fault tolerance or loadsharing, it should be enabled. Whether it is on by default or not, I'm not sure. In case of NATed devices we might run into problems with multihoming. So it might be saver to start with off by default.
@ruengeler Irene will look into this.
