### ISSUE TITLE
neat_set_operations(): pointer copy -> pointer may become invalid if user does not take care

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#208]
neat_set_operations(neat_ctx *mgr, neat_flow *flow, struct neat_flow_operations *ops) just copies a user-provided pointer to the neat_flow_operations structure:
flow->operations = ops;

If the user declares the neat_flow_operations structure, it will be gone later, and the pointer will point to invalid data. What about using a "struct neat_flow_operations operations" inside neat_flow, and copying the contents in neat_set_operations()? This would avoid a user-provided pointer within an internal structure.

**Comment by dreibh** [comment]
Solved. The structure is not only used for providing the callback pointers.

**Comment by oystedal** [comment]
Just for reference, was this closed with no further action taken?
