### ISSUE TITLE
Banning IPv4 or IPv6

### ISSUE THREAD

**Issue by oystedal** [NEAT-project/neat#214]
Properties should be added to ban the use of IPv4 or IPv6.

If possible, this could be filtered by the resolver, or it could be filtered after names have been resolved (in `open_resolve_cb` and `on_candidates_resolved`).

**Comment by evyncke** [comment]
Do we really want to introduce such a property?

It makes little sense for me except for testing

-éric

**Comment by oystedal** [comment]
This was a feature that existed in the old property system that was using bitmasks. It's useful for testing and diagnosing network issues. Other than that, I agree that it makes little sense for applications to use this property as part of normal operation.

**Comment by evyncke** [comment]
:-)

Could we introduce it as 'reserved' or 'hidden' properties?
