### ISSUE TITLE
Improved testing

### ISSUE THREAD

**Issue by oystedal** [NEAT-project/neat#218]
- Unit tests: NEAT could benefit from having unit tests in the long run, especially if external contributions become more frequent. Suggested tools would be [CMocka](https://cmocka.org/) for mocking functions and [Catch](https://github.com/philsquared/Catch) for use as a testing framework.

- Network testing using synthetic traffic: As of currently, the buildbot is testing NEAT on a real network. It might be beneficial to also test NEAT with some synthetic traffic as well, which would open up possibilities to test more exotic networking scenarios. I have no idea if a tool for this exists, it might be necessary to create one from scratch. Tools that may be worth looking into is [Ostinato](http://ostinato.org/), [ScaPy](http://www.secdev.org/projects/scapy/), and maybe also [CORE](https://www.nrl.navy.mil/itd/ncs/products/core).

**Comment by tuexen** [comment]
You could also use [IMUNES](http://imunes.net) for testing NEAT in several network scenarios...

**Comment by dreibh** [comment]
Hi,

On onsdag 30. november 2016 10.24.18 CET oystedal wrote:
> - Network testing using synthetic traffic: As of currently, the buildbot is
> testing NEAT on a real network.

If you are interested, I could create a slice for you in NorNet Core. It would 
provide you access to multi-homed VMs at 21 sites in 7 countries. The machines 
run Linux, support kernel SCTP, DCCP plus the latest Linux MPTCP version. See 
https://www.nntb.no/pub/nornet-configuration/NorNetCore-Sites.html for the full 
site list.

More details on NorNet Core: https://www.nntb.no/ .

-- 
Best regards / Mit freundlichen Gr��en / Med vennlig hilsen

=======================================================================
 Thomas Dreibholz

 Simula Research Laboratory
 Simula Innovation AS, Network Systems Group
 Visiting address: Martin Linges vei 17, 1364 Fornebu, Norway
 Mailing address:  P.O.Box 134, 1325 Lysaker, Norway
-----------------------------------------------------------------------
 E-Mail:     dreibh@simula.no
 Homepage:   http://simula.no/people/dreibh
=======================================================================
