### ISSUE TITLE
For discussion: neat_write()/neat_read() and scatter/gather I/O

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#219]
The NEAT socket API I am writing could make use of scatter/gather I/O via sendmsg()/recvmsg() calls. In order to map scatter/gather I/O to the underlying NEAT core API functions, it would be necessary for neat_write()/neat_read() to provide this feature.

Is scatter/gather I/O a useful feature for the intended NEAT users, in order to avoid unnecessary copying?

**Comment by dreibh** [comment]
If performance is important for NEAT, also support for zero-copy support with sendfile() may be considered as well (see http://www.techrepublic.com/article/use-sendfile-to-optimize-data-transfer/).

**Comment by tuexen** [comment]
The decision was that we do not ficus on zero copy (for now). So do the copy operation above neat in the socket shim layer.

**Comment by dreibh** [comment]
What about moving the scatter/gather copy wrapper into two new Core API functions:
NEAT_EXTERN neat_error_code neat_writev(struct neat_ctx *ctx, struct neat_flow *flow,
                                        const struct iovec *iov, size_t iovlen,
                                        struct neat_tlv optional[], unsigned int opt_count);
NEAT_EXTERN neat_error_code neat_readv(struct neat_ctx *ctx, struct neat_flow *flow,
                                       struct iovec *iov, size_t iovlen, uint32_t *actualAmt,
                                       struct neat_tlv optional[], unsigned int opt_count);
If somebody wants to implement real scatter/gather without copying later, there would at least be suitable API functions already.
