### ISSUE TITLE
Refactor resolver

### ISSUE THREAD

**Issue by kristrev** [NEAT-project/neat#22]
Resolver works fine, but the code is not exactly a beauty. For example:
- The current data structure used when resolving is very inefficient when for example searching. We could for example use a three rooted in the source address.
- Lots of duplicate/very similar code. For example searching for resolve pair and adding a result.

I do not believe in premature optimisations, so this task can be postponed until after the resolver is feature-complete. Changes will only affect the resolver and, as written earlier, it works fine and performs well as-is.

**Comment by weinrank** [comment]
@kristrev 
Is this fixed?

**Comment by kristrev** [comment]
No, I am lazy.

**Comment by weinrank** [comment]
@kristrev now? :smiley:

**Comment by kristrev** [comment]
Nah, still not causing any problems :)
