### ISSUE TITLE
Build with usrsctp failed

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#224]
How to reproduce:
cmake -DUSRSCTP_SUPPORT=1 .
make

Errors:
/home/dreibh/src/neat/neat_core.c: In function ‘neat_write_flush’:
/home/dreibh/src/neat/neat_core.c:3472:81: error: ‘sndinfo’ undeclared (first use in this function)
                                (struct sockaddr *) (flow->sockAddr), 1, (void *)sndinfo,
                                                                                 ^
/home/dreibh/src/neat/neat_core.c:3472:81: note: each undeclared identifier is reported only once for each function it appears in
/home/dreibh/src/neat/neat_core.c: In function ‘neat_write_to_lower_layer’:
/home/dreibh/src/neat/neat_core.c:3720:27: error: ‘sndinfo’ undeclared (first use in this function)
                   (void *)sndinfo, (socklen_t)sizeof(struct sctp_sndinfo), SCTP_SENDV_SNDINFO,
                           ^
/home/dreibh/src/neat/neat_core.c: In function ‘neat_accept_via_usrsctp’:
/home/dreibh/src/neat/neat_core.c:4423:5: error: implicit declaration of function ‘usrsctp_set_upcall’ [-Werror=implicit-function-declaration]
     usrsctp_set_upcall(pollable_socket->usrsctp_socket, handle_upcall, (void*)pollable_socket);
     ^
/home/dreibh/src/neat/neat_core.c: In function ‘handle_connect’:
/home/dreibh/src/neat/neat_core.c:4533:5: error: implicit declaration of function ‘usrsctp_get_events’ [-Werror=implicit-function-declaration]
     if (usrsctp_get_events(sock) & SCTP_EVENT_WRITE) {
     ^
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/neat.dir/neat_core.c.o] Fehler 1
make[1]: *** [CMakeFiles/neat.dir/all] Fehler 2
make: *** [all] Fehler 2

**Comment by dreibh** [comment]
libusrsctp is the latest upstream version, of course.

FYI: I also created Debian/Ubuntu and RPM packaging files and scripts for libusrsctp. See my libusrsctp pull requests here:
- https://github.com/sctplab/usrsctp/pull/116
- https://github.com/sctplab/usrsctp/pull/117

**Comment by weinrank** [comment]
I assume OS is Linux? ;)

NEAT requires a modified version of usrsctp:
https://github.com/NEAT-project/usrsctp-neat
Branch: usrsctpForNeat

Have you installed this version?

**Comment by dreibh** [comment]
I see. Is this documented somewhere? Ideally, of course, the usrsctp-neat modification should be merged upstream. This would simplify things.

CMakeLists.txt should also be extended with some checks for the added functions, in order to produce a useful error message pointing the user to the right version of usrsctp.

**Comment by dreibh** [comment]
I created a pull request for the Debian/Ubuntu/RPM packaging for usrsctp-neat -> https://github.com/NEAT-project/usrsctp-neat/pull/2 . Having this version of usrsctp-neat, neat builds with userland SCTP as expected.
