### ISSUE TITLE
neat_set_operations() should copy the ops struct

### ISSUE THREAD

**Issue by bagder** [NEAT-project/neat#230]
Ok, first it is not documented that right now neat will only copy the *pointer* to the struct set in the third argument to `neat_set_operations()`. So an application will need to keep that ops struct around for the life time of the flow. The life time is not documented either.

I would *strogly* prefer that neat instead copies the contents of the struct into its own local copy so that the application doesn't have to keep it around as it removes the need for the application to keep track of lifetime and when the struct can/should be freed again. Additionally, by neat copying the struct (contents), it can have its own internal representation of that struct differ from the public version of the struct which will help keeping the API/ABI more stable in the long run.

**Comment by dreibh** [comment]
Yes, this was the issue observed in #208.

**Comment by bagder** [comment]
Additionally, NEAT already *updates* the struct in run-time, which thus writes data in the user-provided memory area. That struct can very well be in read-only memory. Not good.
