### ISSUE TITLE
Bug:  neat_accept() + neat_set_operations() => free() on user-allocated structure

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#231]
This is somewhat related to #230 and #208:

The neat_flow_operations structure is handled by the user program. But for neat_accept(), NEAT allocates this structure for a new flow (in do_accept()). This is indicated by newFlow->ownedByCore = 1. synchronous_free() will then free this structure. However, neat_set_operations() does not set ownedByCore=0 when a user-defined structure is provided => synchronous_free() will free the user's structure.

A fix could be:
neat_error_code neat_set_operations(neat_ctx *mgr, neat_flow *flow,
                                    struct neat_flow_operations *ops)
{
    neat_log(NEAT_LOG_DEBUG, "%s", __func__);

    flow->operations = ops;
    flow->ownedByCore = 0;
...

But may be there is a better solution by solving #230?

**Comment by bagder** [comment]
> for neat_accept(), NEAT allocates this structure for a new flow

Whoa, this isn't mentioned in the docs so maybe that could be a step as well?

**Comment by dreibh** [comment]
Created pull request with fix: https://github.com/NEAT-project/neat/pull/240
