### ISSUE TITLE
Memory leak: accept_resolve_cb (neat_core.c:3262)

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#235]
When debugging some server tests, I noticed Valgrind reporting this memory leak:

==27302== 2,144 (376 direct, 1,768 indirect) bytes in 1 blocks are definitely lost in loss record 3 of 4
==27302==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27302==    by 0x504CBF3: accept_resolve_cb (neat_core.c:3262)
==27302==    by 0x5052914: neat_resolver_timeout_shared (neat_resolver.c:365)
==27302==    by 0x5052972: neat_resolver_literal_timeout_cb (neat_resolver.c:381)
==27302==    by 0x5D7023D: uv__run_timers (timer.c:165)
==27302==    by 0x5D64B41: uv_run (core.c:368)
==27302==    by 0x5048B7C: neat_start_event_loop (neat_core.c:179)
==27302==    by 0x4E3AB83: nsa_main_loop (neat-socketapi-internals.c:689)
==27302==    by 0x5265183: start_thread (pthread_create.c:312)
==27302==    by 0x5A8F37C: clone (clone.S:111)

The NEAT context is of course already removed with neat_free_ctx() when finishing the test programs.

**Comment by dreibh** [comment]
The line numbers have changed after some recent merges/commits, but the bug remains:

==26216== 1,104 (392 direct, 712 indirect) bytes in 1 blocks are definitely lost in loss record 4 of 4
==26216==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==26216==    by 0x504C847: accept_resolve_cb (neat_core.c:3592)
==26216==    by 0x50533C4: neat_resolver_timeout_shared (neat_resolver.c:365)
==26216==    by 0x5053422: neat_resolver_literal_timeout_cb (neat_resolver.c:381)
==26216==    by 0x5D7123D: uv__run_timers (timer.c:165)
==26216==    by 0x5D65B41: uv_run (core.c:368)
==26216==    by 0x5048C95: neat_start_event_loop (neat_core.c:186)
==26216==    by 0x4E3AF1D: nsa_main_loop (neat-socketapi-internals.c:740)
==26216==    by 0x5266183: start_thread (pthread_create.c:312)
==26216==    by 0x5A9037C: clone (clone.S:111)

**Comment by dreibh** [comment]
Created pull request with fix: https://github.com/NEAT-project/neat/pull/240

**Comment by weinrank** [comment]
@dreibh update PR repo please.
