### ISSUE TITLE
SIGPIPE on server's sendmsg() call when client aborts connection

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#237]
My test server aborts on SIGPIPE on sendmsg() in neat_core.c:4086 when the connection is aborted by the client:

==21498== Process terminating with default action of signal 13 (SIGPIPE)
==21498==    at 0x526D9BD: ??? (syscall-template.S:81)
==21498==    by 0x504D87A: neat_write_to_lower_layer (neat_core.c:4086)
==21498==    by 0x504DBAC: neat_write (neat_core.c:5293)
==21498==    by 0x4E3BE73: neat_writev (neat-socketapi-io.c:47)
==21498==    by 0x4E3BF2C: nsa_sendmsg (neat-socketapi-io.c:81)
==21498==    by 0x4E3C296: nsa_write (neat-socketapi-io.c:202)
==21498==    by 0x402A5C: handleHTTPCommand(int, unsigned int, char*) (httpserver2-select.cc:83)
==21498==    by 0x403182: ClientList::handleEvent(ClientList::ClientListEntry*) (httpserver2-select.cc:234)
==21498==    by 0x403034: ClientList::handleEvents(fd_set*) (httpserver2-select.cc:208)
==21498==    by 0x40365C: main (httpserver2-select.cc:350)
--21498-- Discarding syms at 0x7cdf2a0-0x7ce4eb3 in /lib/x86_64-linux-gnu/libnss_files-2.19.so due to munmap()

I assume that NEAT should not abort when a client connection breaks, right? Calling sendmsg() with MSG_NOSIGNAL fixes the problem (at least under Linux, not sure about other systems).

**Comment by dreibh** [comment]
The behaviour is the same for both, SCTP and TCP.

**Comment by mcmanus** [comment]
definitely shouldn't generate sigpipe.. MSG_NOSIGNAL is good - masking signals process wide is a scary thing for a process to do.

**Comment by dreibh** [comment]
Created pull request with fix: https://github.com/NEAT-project/neat/pull/240
