### ISSUE TITLE
How to obtain local/remote addresses of a NEAT flow

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#239]
Is there a possibility to obtain the (current) local and remote address(es) of a NEAT flow? This information is needed to implement the socket API functions nsa_getsockname(), nsa_getpeername(), nsa_getladdrs(), nsa_getpaddrs() as well as to return an address with nsa_accept().

**Comment by weinrank** [comment]
There is `neat_get_stats`, it returns a json object with information and statistics about the flow.
We currently don't have a function for your specific needs.

Another starting point is the `neat_geat_property` function, maybe you could extend it.

**Comment by dreibh** [comment]
I added the missing functionality in form of a new function: neat_getlpaddrs(). The corresponding pull request is here: https://github.com/NEAT-project/neat/pull/248 .
