### ISSUE TITLE
More specific error codes for neat_open() call?

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#244]
Is it possible to get more specific error codes from the neat_open() call processing? For implementing nsa_connect(), it would be useful to be able to differentiate between connection refused, no route to host, timeout, etc.. However, the on_error() callback does not get any information on the kind of error.

I also noticed that a connect timeout results in on_error(), not in on_timeout(). The on_timeout() callback is only for sent data, right?

**Comment by tuexen** [comment]
Interesting prefix...

**Comment by dreibh** [comment]
*N*EAT *S*ocket *A*PI -> nsa.

**Comment by weinrank** [comment]
http://weknowmemes.com/wp-content/uploads/2013/06/nsa-meme.jpg

**Comment by weinrank** [comment]
![img_6875](https://cloud.githubusercontent.com/assets/6726222/22566825/c6350f9a-e98d-11e6-9eca-43029a41d493.JPG)

**Comment by bagder** [comment]
`neat_open` can't determine most of those errors since they will happen asynchronously at a later point, but `on_error` could of course be extended to get more error information.
