### ISSUE TITLE
Are porpertyMask, etc. still used?

### ISSUE THREAD

**Issue by ddragana** [NEAT-project/neat#258]
I do not see that the following variables are still used. Are they?

    uint64_t propertyMask;
    uint64_t propertyAttempt;
    uint64_t propertyUsed;

and 

#define NEAT_PROPERTY_OPTIONAL_SECURITY           (1 << 0)
#define NEAT_PROPERTY_REQUIRED_SECURITY           (1 << 1)
#define NEAT_PROPERTY_MESSAGE                     (1 << 2) // stream is default
#define NEAT_PROPERTY_IPV4_REQUIRED               (1 << 3)
#define NEAT_PROPERTY_IPV4_BANNED                 (1 << 4)
#define NEAT_PROPERTY_IPV6_REQUIRED               (1 << 5)
...

**Comment by tuexen** [comment]
I don't know. But I would like to know how to request features like the above via the json format...
@bozakov Can you provide a hint?
So how can I require a message oriented IPv4 based service? This should provide SCTP and UDP candidates (and UDPLite, if we support it, don't know)
@adventureloop Do we support UDPLite (on platforms supporting UDPLite)?

**Comment by bozakov** [comment]
@tuexen there are several options:

1. The JSON request explicitly specifies the desired properties, e.g., 
`{"transport": {"value": "SCTP"}, "remote_name": {"value": "google.de"}}`
  Note, that the transport value can also be a set, if the user is fine to use any of these protocols, e.g.: `{"value": ["SCTP", "UDPLite"]}`
  In the above examples I've omitted the default score and precedence values (1 in both cases). So to indicate that SCTP is mandatory (precedence 2) we can write `{"transport": {"value": "SCTP", "precedence": 2, "score":5}}`.
   
2. The JSON request can also contain more abstract properties, e.g.: `{"transport_type": {"value": "message", "precedence": 2}, ...}`. 
In this case we need to have a policy installed (profile to be precise), which translates `transport_type` into one or more concrete `transport` attributes (ordered, reliable, SCTP, TCP, etc.). A simple example policy is included in `policy/pib/example/transport_reliable.profile`. A policy can also trigger another policy, so it is possible to create farily complex chains. 

Let me know if I should clarify anything else regarding the properties.

**Comment by weinrank** [comment]
I've had a look in the code, it seems that the property masks aren't used any more. 

If no one complains, I'll remove the next week / in Paris.

**Comment by naeemk** [comment]
@tuexen there is a basic UDPLITE support as of 001b1ea and a support for UDPLITE checksum coverage as of 702a640.
