### ISSUE TITLE
logging: thread safety issues

### ISSUE THREAD

**Issue by bagder** [NEAT-project/neat#261]
Neat is really not usable in a multi-threaded situation right now, since the logging options, timing, file etc are all global variables that are set and used without any locking. And `neat_log_init()` itself is even called from within `neat_init_ctx()` so running two separate neat threads will effectively ruin each others log timers and options. This fact is also not documented anywhere.

I propose that we make the logging data properties of the context, so that they can be set differently for each context. IMHO, we should avoid using globals as far as possible.

**Comment by bagder** [comment]
`neat_log()` is currently invoked on 563 places within neat itself. I played with the idea to make it a macro that passes in `ctx` automatically as its first argument to avoid having to change all 563 instances, but A) we don't have a good naming standard so the context isn't called just ctx everywhere and B) there's a set of functions that use logging but doesn't have/use a context that we would need to decide how to handle.

So, this is not easily accomplished with any processor tricks as far as I can see. It makes it a slightly larger effort that I'd like us to reach some sort of agreement on before I would spent efforts on fixing.

**Comment by bagder** [comment]
Issue to solve: `usrsctp_init`is called [here](https://github.com/NEAT-project/neat/blob/master/neat_usrsctp.c#L95) and it passes in a function pointer to a log call that's hard to translate into something using a context.

The only docs I found that describes `usrsctp_init()` is [this](https://github.com/sctplab/usrsctp/blob/master/Manual.md) but it doesn't match the prototype we're using!?

**Comment by tuexen** [comment]
The documentation is outdated, needs to be fixed. `usrsctp_init` takes a function pointer to a logging function. It doesn't know about contexts or such things...

**Comment by bagder** [comment]
And no possibility to pass in a private pointer?

**Comment by tuexen** [comment]
No, unfortunately not. It is just a wrapper around a `printf` function. See [ekr_loop.c](https://github.com/sctplab/usrsctp/blob/master/programs/ekr_loop.c#L259), for example.
It is introduced to provide a way for Chrome and Firefox to include the sctp debug output in their logging environment. No context was required there. See [DataChannel.cpp](https://dxr.mozilla.org/mozilla-central/source/netwerk/sctp/datachannel/DataChannel.cpp#190), for example.

**Comment by bagder** [comment]
Well that's just wrong way to do callbacks. I had to disable the sctp logging for my pull request...

**Comment by tuexen** [comment]
I'm a bit hesitant to change the API, since it will break Chrome and Firefox and other users... I'm wondering why you would need a context in a logging function. At least for Firefox and others it seems to work fine.

**Comment by bagder** [comment]
I've tried to explain the issue above and just reading the code you'll spot this quite easily. Thread-safety and multiple-contexts per thread.

> for Firefox and others it seems to work fine

Well perhaps, but... Even those applications would often prefer to do the logging using their own built-in logging systems rather than to just have a crude printf-logging thing. In your Firefox case I suppose there's only one context so Firefox can get away with using global variables or even global mutexes in their logging function if necessary. I don't think we do.

**Comment by tuexen** [comment]
Any why can't you use a global mutex in the logging function to get the output right if you need it?
I guess this is done in `PR_LogPrint` since it can be called from multiple threads or am I missing something?
We could add another debug callback with a different signature and provide a new function to register it. This would avoid changing the signature of `usrsctp_init`.

**Comment by tuexen** [comment]
Reading the whole thread:

Regarding multithreading: We need to make a clear statement for neat in general, not only for logging.
I think we currently do not protect anything by mutexes...

For logging, I think this comes down to the question: Is the logging "per library", which means we could use global variables (and a global mutex to protect the resources for supporting multithreading) or we consider the logging "per context", where this is not possible and we need to avoid global variables and put them into the context. I think the original design was not a fine grained per context logging.
@weinrank Am I wrong?
This means you want to things:
1. Make logging configurable per context
2. Make neat thread safe
Am I missing something?

**Comment by bagder** [comment]
Yes, that's basically it.

The logging per-context isn't strictly necessary for me, but since I think globals in a library is a recipe for disaster, we must "anchor" the options somewhere (where would we set the logging options?) and the context object seemed like a decent fit. But having the ability to set the level per context may actually be useful in itself too.

My personal view is that making neat anything but thread-safe would be a terrible choice and would seriously hamper adoption. And I don't mean thread-safe by adding mutexes around global variables as that is A) inefficient and B) adds requirements and assumptions I think we should avoid.

**Comment by tuexen** [comment]
The only problem I have with per-context logging is that how to log things that are global to the library? The SCTP stack is one thing but others come up to my mind... I guess several of the places you couldn't find a context to pass in the logging function are possibly incarnations of this.
So we might want to allow to pass a context in for filtering or so, but I guess we need also the possibility to log generic things. Or are you suggesting to allow only context specific logging and disallow logging related to more generic things?
Regarding to multi-threading support we need to decide how fine-grained we want to be. Should it be possible to access a neat flow from different threads? I guess it might make sense to discuss this in Paris... Not sure. I think we left it out initially to get something running first and we didn't need multithreading when using the event loop model...

**Comment by bagder** [comment]
> Or are you suggesting to allow only context specific logging and disallow logging related to more generic things?

The API is made to work with contexts and flows to a rather high degree. Whatever you do with neat, there is a context that the application passes in. There's virtually nothing going on in neat that is "global" or truly disconnected from context. The places in the code where there's no context in neat right now, the ones that my patch comments out, I'm sure in almost all cases *could* get the context passed in.

And instead of me saying how I want things, please tell me how we can do your "global" style of logging while still doing it thread-safe and allowing multiple (independent) contexts per thread.

> Should it be possible to access a neat flow from different threads?

My opinion: no. That's a whole lot of work (and future bugs) for no really strong reason. When I talk about thread-safety for NEAT in  this issue, I'm talking about using separate contexts and separate flows in different threads but at the same time.

**Comment by bagder** [comment]
> we didn't need multithreading when using the event loop model

That's a rather naive assumption I'd like to erase. Two apparent use cases:

1. One event loop per thread for maximum CPU usage
2. Legacy apps already using multi-threading that move to neat, using ` RUN_ONCE`

**Comment by tuexen** [comment]
One thing that is once for the library and not once for a context is the sctp stack. There seems currently be a bug by calling `usrsctp_init` from `neat_init_ctx`, but I guess the neat library has not been tested well with multiple contexts.
Another thing could be (I'm not sure) the management of the IPC to the policy manager.
@bozakov Is the IPC between NEAT and the policy manager per context?
I have no problem in disabling the logging of the SCTP stack since it does not provide any kind of filtering per connection or so.

Regarding thread-safety: So you only want to access different contexts from different threads, right?
So having a "per-context" logging doesn't require any protection. Having a global logging would require protection.

Regarding the naive assumption: I think this was done as an initial assumption for getting things started, not how it should be at the end...

**Comment by bagder** [comment]
> you only want to access different contexts from different threads, right?
So having a "per-context" logging doesn't require any protection

Correct, I use a whole bunch of contexts in parallel. Right now their logs are all messing up each others.

**Comment by weinrank** [comment]
Hey Daniel,

from my perspective it would be a good solution to have a function which initializes the neat library once.
In this function we initialize the logging (logfile and level) as well as the sctp userland stack once.

As you already mentioned: we have several functions without a context which makes things tricky...

**Comment by tuexen** [comment]
I just saw that `neat_log_init` is called in `neat_init_ctx`, which is the same bug as calling there `usrsctp_init`.
If we add something lie `neat_init`, which is called only once and will be used to initialise the logging stuff (and usrsctp), we still have the problem the multiple threads will write to the same fd. But we have  that with your solution, too. So would calling `neat_log_init` only once help you?

**Comment by bagder** [comment]
> would calling neat_log_init only once help you?

I would prefer that we'd lift this discussion and talk about how a library like neat *should* work rather than talking about my specific circumstances.

Moving out the init would make all contexts within the same thread capable of using the same log file fine, but then the delta timing withing the log would be based on the init and thus no longer that relevant to each individual context. So yes, I'd say that would improve things a bit.

But what about multi-threading? Shouldn't applications using neat be able to use contexts from multiple threads? It is really serious restriction to put on a transfer library if that limit is allowed to stick.

**Comment by bagder** [comment]
> from my perspective it would be a good solution to have a function which initializes the neat library once

I think we should, but it wouldn't solve all the issues. It would be similar to @tuexen's idea of not calling the log init from within `neat_init_ctx`.

We should have such a function already for other purposes: namely OpenSSL initialization that's only necessary to once process, not once per context as we do now. It is even [discouraged to get called without using the OpenSSL mutex locks](https://wiki.openssl.org/index.php/Library_Initialization), so this is another area of thread-safety concerns in the current state of the code.

**Comment by tuexen** [comment]
We can talk about how neat should work, especially with relation to multi-threading... But I guess this issue is not the right platform. That is why I suggested to bring it up in Paris... Or do you think this issue is the right place?

My suggestion was to fix bugs we now have, since neat is broken when used with multiple contexts, not matter if it is used single-threaded or multi-threaded. That is why I suggested to add something like `neat_init`...

Are now using a separate fd per thread? I thought that Firefox logs to a single file...

**Comment by kristrev** [comment]
I don't have so much to contribute here, but since I was the one who implemented the version of neat_init_ctx, neat_ctx, etc. My intention was that `neat_init_ctx()` would initialize one `neat_ctx`, and that each `neat_ctx` would be independent so that for example one thread would have one `neat_ctx`. At least in my mind, this is the only pattern that makes sense.

**Comment by bagder** [comment]
For me personally, I'm fine with talking about this wherever, I brought it to the mailing list too but for some reason we never talk about code there to any particular extent. But sure, if there's time for it then we can certainly discuss it in Paris.

> Are now using a separate fd per thread?

I use multiple contexts per thread (as I'm sure many typical legacy apps converting to neat will do). The multi-threading issues have not bitten me yet.

> I thought that Firefox logs to a single file

This is unrelated to how Firefox does logging. This is about how neat works.

Related though: neat should probably offer some sort of log-callback for applications so that Firefox for example could insert the neat logs into its own log system. That would also be useful for applications that want to log (for debugging if nothing else) but don't want to store files and certainly not use stderr.

**Comment by bagder** [comment]
> neat should probably offer some sort of log-callback for applications

... and such a callback would need to be stored somewhere. Like in a context perhaps? :-)

**Comment by tuexen** [comment]
Suggestion:
Felix implements `neat_init`, which calls `usrsctp_init`, `neat_log_init`, and `neat_security_init`.
@bagder @weinrank : OK?

This fixes bugs and improves things for you.

Then there are three issues left:
1. Have a "per-context" logging or a "global" one?
2. How to deal with multi-threading? 
3. How to support external logging systems (for example the one Firefox provides)?

Regarding the first question I would like to know if there is anything except the usrsctp stack not being related to a ctx, like IPC to the policy manager.
@bozakov Can you answer this?
If that is not the case, we can use "per-context" logging and let the user open a separate file for each context. Neat would just disable the logging feature for usesctp.

Then 2. is also fixed, right? At least with the constraint that only a single thread operates on a context at any given time.

Can you then propose an API for 3?

**Comment by bagder** [comment]
It would be less work if we'd do it in a different order:

1. merge my patch
2. make sure there's a context passed to a few places where it could (discuss how we handle the remaining cases)
3. create the global init/free functions (and document it not being thread-safe and that it used be used only once per process)

This would then make it really ease to provide an API (and associated code) that sets a log callback instead of a file name for logging.

**Comment by bagder** [comment]
> if there is anything except the usrsctp stack not being related to a ctx

Surely it *is* related to a context, it just doesn't pass the context pointer to the log function?

**Comment by tuexen** [comment]
I don't see how the stack is related to a context. A set of flows might be, but not the stack as a whole.
Which context would own the raw socket used by all SCTP associations (of all flows of all contexts)
Therefore the stack doesn't provide the functionality of logging on a per end-point granularity.
You only turn it on when you are debugging and then you might be interested in a lot of things. You can  filter later...

**Comment by weinrank** [comment]
Okay, after thinking about the logging function for a while, I think we should have it per context.

### Pros for context
* time elapsed per ctx
* log level per ctx
* we can distinguish the different ctxs - this is one of the most important pros for me

### Cons against context
* not all functions have a ctx (yet)
* more coding afford

**Comment by bagder** [comment]
> I don't see how the stack is related to a context.

Not the stack itself perhaps, but all network activities the stack is doing are associated with flows and contexts as without them the stack wouldn't be run!

**Comment by bozakov** [comment]
@tuexen The PM IPC is currently agnostic to contexts (a single instance of the PM replies to the Unix socket over which the request was received).

**Comment by tuexen** [comment]
@bagder Not all activities are related with flows and for some activities you don't know the flows. For example if you receive a packet not being related to any flow, you would have to send a packet containing an ABORT chunk (the equivalent of a TCP reset). One example for the case where you don't know the flow yet is all the packet handling done before you found the flow. Checking checksums, doing other  validation, looking up the flow. I'm not saying the none activity is related to a flow, just that there are cases where you have no flow, sometimes not yet.
But I'm fine with having per context logging and just not support the logging in the userland stack.
@bozakov Thanks for the answer. I think the IPC between the neat library and the PM should not be per context... So We just can't use the logging framework there...

**Comment by bagder** [comment]
> Not all activities are related with flows

Right, but I said *flows and contexts* and since there's a context pointer in the `neat_start_event_loop()` call, at least that context would be associated with the SCTP traffic.

> think the IPC between the neat library and the PM should not be per context

On the neat library's side, isn't that communication is associated with a context? Or is the PM setting "global" variables?

**Comment by bagder** [comment]
#263 was merged
