### ISSUE TITLE
on_disconnected callback

### ISSUE THREAD

**Issue by weinrank** [NEAT-project/neat#27]
I suggest to add an **on_disconnect** callback. 
While writing some applications with the neat api i missed this callback when a client disconnects from a server.

**Comment by kristahi** [comment]
I think the CLOSE event from D1.2 sect. 3.2.4 should fit the bill, right?

It's implemented on the oystedal/neat-logic branch now, as `on_close`.

**Comment by tuexen** [comment]
So why not provide a pull request for adding `on_close()` to get it in the master branch?

**Comment by kristahi** [comment]
We will do so ASAP, it is however part of a larger series of changes not quite ready for master yet.

If you need the feature "yesterday", I can see if I can separate it and cherry-pick it to master faster.

**Comment by tuexen** [comment]
I don't need it "yesterday" but prefer small pull requests focusing a one thing...

**Comment by kristahi** [comment]
`on_close` is now available in master.

**Comment by weinrank** [comment]
Great, i will implement it in the samples and test it.
