### ISSUE TITLE
on_all_written Should always be called for a neat_write when the callback is set

### ISSUE THREAD

**Issue by adventureloop** [NEAT-project/neat#272]

**Comment by weinrank** [comment]
example?

**Comment by bozakov** [comment]
If you could have a loot at the socket_options branch (#269) there is an example `examples/client_data.c`. If line 245 is uncommented `//ops.on_all_written = on_all_written;
` on_all_written never gets called.

**Comment by adventureloop** [comment]
@weinrank discussed this yesterday. `on_all_written` is only triggered when neat has had to buffer the write. We think the callback should always be triggered after a write, when the callback is set.

**Comment by mcmanus** [comment]
what tom says makes sense to me.
