### ISSUE TITLE
NXDOMAIN takes 30 seconds to return error

### ISSUE THREAD

**Issue by bagder** [NEAT-project/neat#288]
# I used

`./client_http_get this-site-doesnt-exist.haxx.se`

# I expected

The code to exit quickly since the host name does not exist. nslookup and dig both return NXDOMAIN for it instantly. Instead it takes 30 seconds for it to exit.

**Comment by bagder** [comment]
In addition, when I mistakenly add crap to the host name, like passing in `http://example.com` instead of just `example.com`, that too takes a long time...

**Comment by kristrev** [comment]
I will take a look at this during the hackathon.

**Comment by kristrev** [comment]
Fixed by starting the default 100ms timer if we get an error back from the DNS sever. It could be that the logic here should be tweaked a bit (increase timer, check number of servers that send bad replies, ...) in case other DNS servers will reply with a valid answer to the query.
