### ISSUE TITLE
neat_getlpaddrs requires free() on data returned by library

### ISSUE THREAD

**Issue by bagder** [NEAT-project/neat#290]
Generally it is an anti-pattern to return memory over to the application and require that the application calls `free()` on it.

First, it removes the ability for the library to use its own malloc system, possibly with debug hooks, leak detection and more. Then, it prevents neat to work properly on systems that by default use different memory allocating systems or ownership in libraries vs application (like windows).

The simplest way to avoid this problem is to provide a `neat_free` function to use when freeing allocated data returned by neat.

**Comment by dreibh** [comment]
Sounds reasonable. For neat_getlpaddrs(), I will add a corresponding function neat_freelpaddrs().

**Comment by dreibh** [comment]
I created a pull request: https://github.com/NEAT-project/neat/pull/298 .

**Comment by weinrank** [comment]
#298 merged...
