### ISSUE TITLE
The buildbot page is down

### ISSUE THREAD

**Issue by bagder** [NEAT-project/neat#293]
Go to http://buildbot.nplab.de:28010/waterfall

It shows a huge stacktrace instead of the actual buildbot table and build results. The start of it shows:

 twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'sqlalchemy.exc.OperationalError'>: (OperationalError) disk I/O error u'SELECT buildrequests.id, buildrequests.buildsetid, buildrequests.buildername, buildrequests.priority, buildrequests.complete, buildrequests.results, buildrequests.submitted_at, buildrequests.complete_at, buildrequest_claims.brid, buildrequest_claims.objectid, buildrequest_claims.claimed_at \nFROM buildrequests LEFT OUTER JOIN buildrequest_claims ON buildrequests.id = buildrequest_claims.brid \nWHERE buildrequest_claims.claimed_at IS NULL AND buildrequests.complete = ? AND buildrequests.buildername = ?' (0, 'freebsd-arm') /usr/local/lib/python2.7/threading.py:801:__bootstrap_inner /usr/local/lib/python2.7/threading.py:754:run /usr/local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py:46:work /usr/local/lib/python2.7/site-packages/twisted/_threads/_team.py:190:doWork --- <exception caught here> --- /usr/local/lib/python2.7/site-packages/twisted/python/threadpool.py:246:inContext /usr/local/lib/python2.7/site-packages/twisted/python/threadpool.py:262:<lambda> /usr/local/lib/python2.7/site-packages/twisted/python/context.py:118:callWithContext /usr/local/lib/python2.7/site-packages/twisted/python/context.py:81:callWithContext /usr/local/lib/python2.7/site-packages/buildbot/db/pool.py:191:__thd /usr/local/lib/python2.7/site-packages/buildbot/db/buildrequests.py:120:thd /usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1449:execute /usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1584:_execute_clauseelement /usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1698:_execute_context /usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1691:_execute_context /usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:331:do_execute ]]

**Comment by weinrank** [comment]
Looks like the HDD is full, will fix it until tomorrow.

**Comment by weinrank** [comment]
Disk was full, should be fine now.
