### ISSUE TITLE
Status of TLS support?

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#297]
How is the status of TLS support in NEAT? As far as I can see, the only server example supposed to support TLS is server_echo.c. However, a call of
"server_echo -P NEAT_PROPERTY_REQUIRED_SECURITY,NEAT_PROPERTY_TCP_REQUIRED,NEAT_PROPERTY_IPV4_REQUIRED -v 2 -p cert.pem"
results in:
Unable to read properties from NEAT_PROPERTY_REQUIRED_SECURITY,NEAT_PROPERTY_TCP_REQUIRED,NEAT_PROPERTY_IPV4_REQUIRED.
(I assume the properties format has changed, and the instruction how to use server_echo is out of date)?

Using JSON properties also does not turn on security. It seems that neat_security_install() is never called.

The code in do_accept() seems to be broken:
            if ((false) &&
                (newFlow->socket->stack == NEAT_STACK_TCP)) {
                neat_log(ctx, NEAT_LOG_DEBUG, "TCP Server Security");
                if (neat_security_install(newFlow->ctx, newFlow) != NEAT_OK) {

"(false) && something" is never true.

**Comment by Cylra** [comment]
Is there any news on TLS support in NEAT? Do you have a working example for the server side?

**Comment by weinrank** [comment]
Fixes by #334
