### ISSUE TITLE
Bug in neat_accept: tutorial bug in minimal_server.c

### ISSUE THREAD

**Issue by odonnellf** [NEAT-project/neat#301]
New to the team so I'm just becoming familiar with the architecture. When running the minimal_server executable however (the same as that found in the tutorial documentation or in the examples folder), the server will very rarely but occasionally hang up after a call to neat_run_event_cb:

$ ./minimal_server
[ 0.000001][INF] neat_log_init - opening logfile ...
[ 0.000509][DBG] neat_init_ctx
[ 0.000686][DBG] neat_new_flow
[ 0.001541][DBG] neat_set_operations
[ 0.001551][DBG] updatePollHandle
[ 0.001561][DBG] neat_accept
[ 0.001572][DBG] neat_add_event_cb
[ 0.001580][INF] neat_add_event_cb - Added new callback for event type 0
[ 0.001590][DBG] neat_add_event_cb
[ 0.001597][INF] neat_add_event_cb - Added new callback for event type 2
[ 0.001650][DBG] neat_add_event_cb
[ 0.001660][INF] neat_add_event_cb - Added new callback for event type 0
[ 0.001694][DBG] neat_start_event_loop
[ 0.001703][DBG] accept_resolve_cb
[ 0.001735][INF] Available src-addresses:
[ 0.001870][INF] IPv4: 10.73.64.71/24
[ 0.001880][INF] IPv4: 127.0.0.1/8
[ 0.001890][DBG] neat_run_event_cb
[ 0.002294][INF] Available src-addresses:
[ 0.002312][INF] IPv6: ::1/128 pref 4294967295 valid 4294967295
[ 0.002323][INF] IPv4: 10.73.64.71/24
[ 0.002333][INF] IPv4: 127.0.0.1/8
[ 0.002343][DBG] neat_run_event_cb

***This hangs here until the process needs to be cancelled and the provided socat command to test port 5000 obviously refuses connection***
![minimal_server](https://cloud.githubusercontent.com/assets/26623972/24605037/16804e42-185f-11e7-9a87-15e3bb932fa4.PNG)

For the most part the file works as expected but from repeated testing the above will occasionally occur. I just wanted to bring this to attention, maybe see if anyone else can manage to replicate it? It could be a quick fix but it's something I noticed. I'm using a Ubuntu 16.04 virtual machine FYI

**Comment by bozakov** [comment]
The callback `accept_resolve_cb` in `neat_core.c` _sometimes_ receives a code 2 (NEAT_RESOLVER_ERROR) causing the callback to return with a NEAT_ERROR_DNS, which is seems unhandled.

**Comment by weinrank** [comment]
I've ran into the same error today and it seems that the error is related to the way Linux resolves the locally available IP addresses. 

The new listening flow starts "operating" before the local address candidates are available.

@kristrev can you fix this?

**Comment by kristrev** [comment]
Please provide steps for how to reproduce the issue and I will take a look.

Kristian

**Comment by weinrank** [comment]
```
/tneat -v 4 -P prop_default.json
```

Output on my Ubuntu 17.04 machine:
```
➜  examples git:(master) ✗ ./tneat -v 4 -P prop_default.json
option - log level: 4
option - properties: {
    "transport": [
        {
            "value": "SCTP",
            "precedence": 1
        },
        {
            "value": "TCP",
            "precedence": 1
        }
    ]
}

role: passive
[   0.000001][INF] neat_log_init - opening logfile ...
[   0.000045][DBG] neat_init_ctx
[   0.000310][DBG] neat_new_flow
[   0.000355][DBG] neat_set_operations
[   0.000371][DBG] updatePollHandle
[   0.000390][DBG] neat_set_property
[   0.000440][DBG] neat_accept
[   0.000461][DBG] neat_add_event_cb
[   0.000482][INF] neat_add_event_cb - Added new callback for event type 0
[   0.000506][DBG] neat_add_event_cb
[   0.000527][INF] neat_add_event_cb - Added new callback for event type 2
[   0.000607][DBG] neat_add_event_cb
[   0.000625][INF] neat_add_event_cb - Added new callback for event type 0
[   0.000656][DBG] neat_start_event_loop
[   0.000678][DBG] accept_resolve_cb
[   0.000734][INF] Available src-addresses:
[   0.000760][INF] 	IPv4: 127.0.0.1/8
[   0.000781][DBG] neat_run_event_cb
[   0.000984][INF] Available src-addresses:
[   0.001006][INF] 	IPv4: 212.201.121.90/27
[   0.001030][INF] 	IPv4: 127.0.0.1/8
[   0.001053][DBG] neat_run_event_cb
[   0.001126][INF] Available src-addresses:
[   0.001141][INF] 	IPv4: 10.0.1.144/24
[   0.001169][INF] 	IPv4: 212.201.121.90/27
[   0.001195][INF] 	IPv4: 127.0.0.1/8
[   0.001223][DBG] neat_run_event_cb
[   0.001294][INF] Available src-addresses:
[   0.001320][INF] 	IPv6: ::1/128 pref 4294967295 valid 4294967295
[   0.001345][INF] 	IPv4: 10.0.1.144/24
[   0.001372][INF] 	IPv4: 212.201.121.90/27
[   0.001396][INF] 	IPv4: 127.0.0.1/8
[   0.001423][DBG] neat_run_event_cb
```

There are no listening sockets open.
Sometimes this happens, sometimes not - seems to be a race condition.

**Comment by kristrev** [comment]
Great, thanks! Will take a look before or in Cork. Hopefully something
trivial.

Kristian

**Comment by kristrev** [comment]
The code error is triggered by @ruengeler in commit ea6d6c220d89db082bcd8f454ad07f28f0d6f5f8, most likely because commit was only tested properly on BSD and BSD has synchronous address reading (if I remember correctly).

Problem is that the commit sets the literal timeout to 1ms (down from 1000), which is too short for the source address list on Linux to be popluated (it is async). I will implemented some kind of retry mechanism.

**Comment by kristrev** [comment]
See PR #325 for the fix. There seems to be some issue with buildbot, so waiting for the buildbot to be back and tests to be run before merging.

**Comment by naeemk** [comment]
@kristrev: can this be closed?
