### ISSUE TITLE
Support for Deepin Linux

### ISSUE THREAD

**Issue by jackChengX** [NEAT-project/neat#311]
Is there support for NEAT builds with Deepin Linux (https://www.deepin.org/en/)?

**Comment by dreibh** [comment]
Deepin Linux 15.4 is based on Ubuntu 16.04 (Xenial Xerus). It is therefore straightforward to add the Ubuntu PPA for the binary package builds:

1. Add the following lines to /etc/apt/sources.list:
deb http://ppa.launchpad.net/dreibh/ppa/ubuntu xenial main 
deb-src http://ppa.launchpad.net/dreibh/ppa/ubuntu xenial main 

2. Add the public key:
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 916C56E0

Then:
sudo apt update
sudo apt libneat-socketapi-dev
(or other NEAT package(s) you would like to install)

**Comment by dreibh** [comment]
Note: Deepin Linux 15.3 is based on Ubuntu 14.04 (Trusty Tahr). The Ubuntu 14.04 version of libuv is too old -> NEAT will not work here. You could upgrade to Deepin Linux 15.4.
