### ISSUE TITLE
Status of MPTCP and CMT-SCTP support?

### ISSUE THREAD

**Issue by Cylra** [NEAT-project/neat#312]
How is the status of MPTCP and CMT-SCTP (with libusrsctp) support in NEAT? I would like to be able to make a per-connection choice of MPTCP/TCP or CMT-SCTP/regular SCTP.

**Comment by weinrank** [comment]
MPTCP and CMT-SCTP integrated in the master branch.
The prop_mptcp.json and prop_sctp_multihomed.json property files should help.
