### ISSUE TITLE
Fedora 26/Rawhide build issues when building with usrsctp

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#319]
Issue 1:

home/nornetpp/src/neat/neat_core.c: In Funktion »io_readable«:
/home/nornetpp/src/neat/neat_core.c:1280:19: Fehler: Deklaration von »len« überdeckt einen vorhergehenden lokalen Bezeichner [-Werror=shadow]
         socklen_t len;
                   ^~~
/home/nornetpp/src/neat/neat_core.c:1270:15: Anmerkung: verdeckte Deklaration ist hier
     socklen_t len;
               ^~~

Issue 2:

In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:88:18: Fehler: In Konflikt stehende Typen für »sctp_assoc_t«
 typedef uint32_t sctp_assoc_t;
                  ^~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:42:15: Anmerkung: Vorherige Deklaration von »sctp_assoc_t« war hier
 typedef __s32 sctp_assoc_t;
               ^~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:259:8: Fehler: Redefinition von »struct sctp_assoc_change«
 struct sctp_assoc_change {
        ^~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:197:8: Anmerkung: ursprünglich hier definiert
 struct sctp_assoc_change {
        ^~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:287:8: Fehler: Redefinition von »struct sctp_paddr_change«
 struct sctp_paddr_change {
        ^~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:233:8: Anmerkung: ursprünglich hier definiert
 struct sctp_paddr_change {
        ^~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:307:8: Fehler: Redefinition von »struct sctp_remote_error«
 struct sctp_remote_error {
        ^~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:269:8: Anmerkung: ursprünglich hier definiert
 struct sctp_remote_error {
        ^~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:317:8: Fehler: Redefinition von »struct sctp_shutdown_event«
 struct sctp_shutdown_event {
        ^~~~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:318:8: Anmerkung: ursprünglich hier definiert
 struct sctp_shutdown_event {
        ^~~~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:325:8: Fehler: Redefinition von »struct sctp_adaptation_event«
 struct sctp_adaptation_event {
        ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:332:8: Anmerkung: ursprünglich hier definiert
 struct sctp_adaptation_event {
        ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:334:8: Fehler: Redefinition von »struct sctp_pdapi_event«
 struct sctp_pdapi_event {
        ^~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:347:8: Anmerkung: ursprünglich hier definiert
 struct sctp_pdapi_event {
        ^~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:348:8: Fehler: Redefinition von »struct sctp_authkey_event«
 struct sctp_authkey_event {
        ^~~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:364:8: Anmerkung: ursprünglich hier definiert
 struct sctp_authkey_event {
        ^~~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:363:8: Fehler: Redefinition von »struct sctp_sender_dry_event«
 struct sctp_sender_dry_event {
        ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:376:8: Anmerkung: ursprünglich hier definiert
 struct sctp_sender_dry_event {
        ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:441:7: Fehler: Redefinition von »union sctp_notification«
 union sctp_notification {
       ^~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:407:7: Anmerkung: ursprünglich hier definiert
 union sctp_notification {
       ^~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:461:8: Fehler: Redefinition von »struct sctp_event_subscribe«
 struct sctp_event_subscribe {
        ^~~~~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:387:8: Anmerkung: ursprünglich hier definiert
 struct sctp_event_subscribe {
        ^~~~~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:592:8: Fehler: Redefinition von »struct sctp_initmsg«
 struct sctp_initmsg {
        ^~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:126:8: Anmerkung: ursprünglich hier definiert
 struct sctp_initmsg {
        ^~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:599:8: Fehler: Redefinition von »struct sctp_rtoinfo«
 struct sctp_rtoinfo {
        ^~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:475:8: Anmerkung: ursprünglich hier definiert
 struct sctp_rtoinfo {
        ^~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:606:8: Fehler: Redefinition von »struct sctp_assocparams«
 struct sctp_assocparams {
        ^~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:488:8: Anmerkung: ursprünglich hier definiert
 struct sctp_assocparams {
        ^~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:615:8: Fehler: Redefinition von »struct sctp_setprim«
 struct sctp_setprim {
        ^~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:518:8: Anmerkung: ursprünglich hier definiert
 struct sctp_setprim {
        ^~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:621:8: Fehler: Redefinition von »struct sctp_setadaptation«
 struct sctp_setadaptation {
        ^~~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:532:8: Anmerkung: ursprünglich hier definiert
 struct sctp_setadaptation {
        ^~~~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:625:8: Fehler: Redefinition von »struct sctp_paddrparams«
 struct sctp_paddrparams {
        ^~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:560:8: Anmerkung: ursprünglich hier definiert
 struct sctp_paddrparams {
        ^~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:646:8: Fehler: Redefinition von »struct sctp_assoc_value«
 struct sctp_assoc_value {
        ^~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:644:8: Anmerkung: ursprünglich hier definiert
 struct sctp_assoc_value {
        ^~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:670:8: Fehler: Redefinition von »struct sctp_hmacalgo«
 struct sctp_hmacalgo {
        ^~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:593:8: Anmerkung: ursprünglich hier definiert
 struct sctp_hmacalgo {
        ^~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:684:8: Fehler: Redefinition von »struct sctp_sack_info«
 struct sctp_sack_info {
        ^~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:638:8: Anmerkung: ursprünglich hier definiert
 struct sctp_sack_info {
        ^~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:696:8: Fehler: Redefinition von »struct sctp_paddrinfo«
 struct sctp_paddrinfo {
        ^~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:658:8: Anmerkung: ursprünglich hier definiert
 struct sctp_paddrinfo {
        ^~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:706:8: Fehler: Redefinition von »struct sctp_status«
 struct sctp_status {
        ^~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:694:8: Anmerkung: ursprünglich hier definiert
 struct sctp_status {
        ^~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:738:8: Fehler: Redefinition von »struct sctp_authchunks«
 struct sctp_authchunks {
        ^~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:713:8: Anmerkung: ursprünglich hier definiert
 struct sctp_authchunks {
        ^~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:749:8: Fehler: Redefinition von »struct sctp_setpeerprim«
 struct sctp_setpeerprim {
        ^~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:505:8: Anmerkung: ursprünglich hier definiert
 struct sctp_setpeerprim {
        ^~~~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:755:8: Fehler: Redefinition von »struct sctp_authchunk«
 struct sctp_authchunk {
        ^~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:577:8: Anmerkung: ursprünglich hier definiert
 struct sctp_authchunk {
        ^~~~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:807:8: Fehler: Redefinition von »struct sctp_authkey«
 struct sctp_authkey {
        ^~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_security.c:10:0:
/usr/include/netinet/sctp.h:604:8: Anmerkung: ursprünglich hier definiert
 struct sctp_authkey {
        ^~~~~~~~~~~~
In file included from /home/nornetpp/src/neat/neat_internal.h:23:0,
                 from /home/nornetpp/src/neat/neat_security.c:13:
/usr/include/usrsctp.h:814:8: Fehler: Redefinition von »struct sctp_authkeyid«
 struct sctp_authkeyid {
        ^~~~~~~~~~~~~~

**Comment by dreibh** [comment]
Issue 1 can be solved easily. For the second declaration of socklen_t len:
#if !defined(USRSCTP_SUPPORT)
        socklen_t len;
#endif

**Comment by dreibh** [comment]
Issue 2 probably needs a check for kernel SCTP headers and an exisiting declaration of sctp_assoc_t within usrsctp.

**Comment by dreibh** [comment]
I fixed issue 1 as part of pull request #320. The authors of usrsctp need to have a look at issue 2.

**Comment by dreibh** [comment]
Any thoughts on the sctp_assoc_t type conflict?

**Comment by dreibh** [comment]
If there is interest in a Fedora 26 VM image (OVA file for VirtualBox), I can provide it.

**Comment by dreibh** [comment]
A little bit of further debugging on the sctp_assoc_t issue:

The only place where it causes a problem is neat_security.c, if NEAT_SCTP_DTLS is defined (include netinet/sctp.h). Commenting out this include just results in build errors when printing debug output for SCTP_REMOTE_ERROR and SCTP_SEND_FAILED notifications. Also commenting out these debug outputs let the build finish.

**Comment by tuexen** [comment]
I think you should not use the kernel SCTP stack and the SCTP userland stack at the same time. Also don't include both headers... That is a current limitation. The userland stack is intended to be a replacement for a kernel stack, not something that can coexist...

**Comment by dreibh** [comment]
Then, this is probably a general bug of the CMakeLists.txt (not related to Fedora). It seems that both, kernel SCTP and user-space SCTP, are compiled in.

**Comment by weinrank** [comment]
No, it's not a general bug since you have to enable usrsctp-support manually in the CMake file.

**Comment by dreibh** [comment]
If USRSCTP_SUPPORT=1 is incompatible with kernel SCTP support, then CMakeLists.txt should disable building with kernel SCTP support.

**Comment by weinrank** [comment]
PR welcome!
