### ISSUE TITLE
How to port SCTP application using 1-to-many-style API?

### ISSUE THREAD

**Issue by kuang1521793003** [NEAT-project/neat#324]
I am having an SCTP application using the 1-to-many-style API. The libneat-socketapi seems to be not working in 1-to-many-style mode?

**Comment by dreibh** [comment]
A 1-to-many-style API (UDP-like) is not supported, yet. For SCTP, it should be quite straightforward to realise this functionality. This would make it easy to port SCTP applications (e.g. RSerPool) to NEAT.

However, it may be useful to think about this functionality in a more generic way, and implement some generic message framing (protocol-independent, i.e. particularly also supporting TCP/MPTCP) into the underlying callback API. Then, a 1-to-many-style sockets API could also be used with TCP/MPTCP.

I suggest to discuss this topic during the NEAT Plenary Meeting in Cork.

**Comment by naeemk** [comment]
@dreibh: any update from Cork on this?
