### ISSUE TITLE
Compile issue with SCTP_MULTISTREAMING=1

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#341]
Compile issue with SCTP_MULTISTREAMING=1:

/home/dreibh/src/neat/neat_core.c: In function ‘io_readable’:
/home/dreibh/src/neat/neat_core.c:1642:33: error: ‘struct neat_flow’ has no member named ‘ownedByCore’
                 multistream_flow->ownedByCore               = 1;
                                 ^
/home/dreibh/src/neat/neat_core.c:1644:61: error: incompatible types when assigning to type ‘struct neat_flow_operations’ from type ‘void *’
                 multistream_flow->operations                = calloc(1, sizeof(struct neat_flow_operations));
                                                             ^
/home/dreibh/src/neat/neat_core.c:1645:21: error: wrong type argument to unary exclamation mark
                 if (!multistream_flow->operations)
                     ^
/home/dreibh/src/neat/neat_core.c:1663:59: error: incompatible type for argument 1 of ‘multistream_flow->operations.on_connected’
                 multistream_flow->operations.on_connected(multistream_flow->operations);
                                                           ^
/home/dreibh/src/neat/neat_core.c:1663:59: note: expected ‘struct neat_flow_operations *’ but argument is of type ‘struct neat_flow_operations’
[ 12%] Linking C static library libneat-socketapi-static.a
/home/dreibh/src/neat/neat_core.c:1693:58: error: incompatible type for argument 1 of ‘multistream_flow->operations.on_readable’
                 multistream_flow->operations.on_readable(multistream_flow->operations);
                                                          ^
/home/dreibh/src/neat/neat_core.c:1693:58: note: expected ‘struct neat_flow_operations *’ but argument is of type ‘struct neat_flow_operations’
/home/dreibh/src/neat/neat_core.c: In function ‘io_readable’:
/home/dreibh/src/neat/neat_core.c:1642:33: error: ‘struct neat_flow’ has no member named ‘ownedByCore’
                 multistream_flow->ownedByCore               = 1;
                                 ^
/home/dreibh/src/neat/neat_core.c:1644:61: error: incompatible types when assigning to type ‘struct neat_flow_operations’ from type ‘void *’
                 multistream_flow->operations                = calloc(1, sizeof(struct neat_flow_operations));
                                                             ^
/home/dreibh/src/neat/neat_core.c:1645:21: error: wrong type argument to unary exclamation mark
                 if (!multistream_flow->operations)
                     ^
/home/dreibh/src/neat/neat_core.c:1663:59: error: incompatible type for argument 1 of ‘multistream_flow->operations.on_connected’
                 multistream_flow->operations.on_connected(multistream_flow->operations);
                                                           ^
/home/dreibh/src/neat/neat_core.c:1663:59: note: expected ‘struct neat_flow_operations *’ but argument is of type ‘struct neat_flow_operations’
/home/dreibh/src/neat/neat_core.c:1693:58: error: incompatible type for argument 1 of ‘multistream_flow->operations.on_readable’
                 multistream_flow->operations.on_readable(multistream_flow->operations);
                                                          ^
/home/dreibh/src/neat/neat_core.c:1693:58: note: expected ‘struct neat_flow_operations *’ but argument is of type ‘struct neat_flow_operations’
/home/dreibh/src/neat/neat_core.c: In function ‘neat_sctp_handle_reset_stream’:
/home/dreibh/src/neat/neat_core.c:7159:50: error: incompatible type for argument 1 of ‘flow->operations.on_readable’
                     flow->operations.on_readable(flow->operations);
                                                  ^
/home/dreibh/src/neat/neat_core.c:7159:50: note: expected ‘struct neat_flow_operations *’ but argument is of type ‘struct neat_flow_operations’
/home/dreibh/src/neat/neat_core.c: In function ‘neat_sctp_handle_reset_stream’:
/home/dreibh/src/neat/neat_core.c:7159:50: error: incompatible type for argument 1 of ‘flow->operations.on_readable’
                     flow->operations.on_readable(flow->operations);
                                                  ^
/home/dreibh/src/neat/neat_core.c:7159:50: note: expected ‘struct neat_flow_operations *’ but argument is of type ‘struct neat_flow_operations’

**Comment by weinrank** [comment]
I'll fix it.

**Comment by weinrank** [comment]
fixed by #342
