### ISSUE TITLE
(travis) CI integration?

### ISSUE THREAD

**Issue by bagder** [NEAT-project/neat#364]
github offers a fancy system for the CI builds to submit back status information so that pull-requests and ordinary pushes can immediately show if they failed to build/test. One such easy-to-integrate with CI is travis-ci, which provides CPU for free for such builds, and it helps running tests and builds automatically on pull requests and thus reducing work for reviewers etc.

Please enable travis-ci builds, and we can work on polishing a first config for it to build neat on Linux and osx at least.

(I'm not a member of the @neat-project organization on github so I can't set it up myself.)

**Comment by tuexen** [comment]
We are currently using buildbots:
https://github.com/NEAT-project/neat#buildbots-fire
which is integrated in GitHub in a way that commits on any branch trigger a build.
Are there benefits from using travis instead of the buildbot infrastructure we are currently using?

**Comment by bagder** [comment]
First off, they can (and should?) both be used. No need to switch off anything that works. So adding this wouldn't take away any existing functionality.

There are several benefits to integrate better with github. Some that comes mind:
1. Visual feedback on pull-requests and pushes when breaking things. Reviewers can then mostly ignore PRs until they're at least green.
2. It makes it easy to get an overview so I can create N PRs and then see how they all fare in the github PR list. No need to handicraft a specific URL for each branch.
3. The above works for **all** contributors. The current build-bot system only works for members who can create branches in the neat repository, not for casual outside contributors.

**Comment by weinrank** [comment]
> (I'm not a member of the @NEAT-project organization on github so I can't set it up myself.)
Now you're! :)

**Comment by tuexen** [comment]
There is a reason we don't test arbitrary PRs: Part of the testing is letting clients talk to external servers (for doing run time tests). So we limit this to project members.

Would it help you to become a member of the project such that you can create your own branches? Seems to be the simplest solution...

**Comment by bagder** [comment]
> Part of the testing is letting clients talk to external servers

The solution to that is of course to make sure we have a set of tests that don't do that. Besides, the initial work could for example just build neat on Linux and osx and make sure that they work.

> Would it help you to become a member of the project such that you can create your own branches

I am and I can, but that's more work/more inconvenient, less visible on github and it doesn't help outside contributors.

**Comment by tuexen** [comment]
Doesn't require "make sure that they work" an example, I can change via a PR, which talks to other nodes?

Since you are a project member, can't you add the stuff you think is necessary?

**Comment by bagder** [comment]
> Since you are a project member, can't you add the stuff you think is necessary?

No, since it requires access from an "organization owner/admin" something (that I'm not) to be allowed to show status on the github repo. I've now requested access from travis to create a travis-CI job for neat to show you the benefits.

**Comment by weinrank** [comment]
I've set your level to "Admin", are you now able to change the settings?

**Comment by bagder** [comment]
It doesn't seem to be enough, no. I'm a member of seven other github organizations and I can add repos from them, I think I need to be made a member of the organization, not just an admin of this particular repository to get that power granted. Right now it  seems only @weinrank is a member: https://github.com/orgs/NEAT-project/people

**Comment by tuexen** [comment]
@bagder There are 33 members in the project, just only one (@weinrank) is a public member. I don't see you being listed there. Maybe that is a problem... Not sure how to add you (or if I'm able to do that).

**Comment by bagder** [comment]
It's all very confusing really...

**Comment by weinrank** [comment]
![image](https://user-images.githubusercontent.com/6726222/29028323-2eec4e12-7b84-11e7-9193-adf30c9617b3.png)

Just to get sure: When opening the "neat" repo, you don't see the "Settings" tab?

**Comment by bagder** [comment]
Yes, but that's settings for the repository, not for the organization.

**Comment by weinrank** [comment]
![image](https://user-images.githubusercontent.com/6726222/29028444-a599632e-7b84-11e7-89a5-bacdde0816c7.png)

Aren't you looking for the "Webhook" section? :)

**Comment by weinrank** [comment]
Or the "Integration & Services" section...

**Comment by bagder** [comment]
I go to travis-ci.org and try to add the neat repo. It requires access to the organization that I don't possess so I've requested said access.

It is not just a webhook, as then I could add it myself and travis wouldn't ask for said access.

Go ahead and look for yourself.

**Comment by bagder** [comment]
Working on this now in #369, closing this.
