### ISSUE TITLE
"hard coded" compiler options in cmake

### ISSUE THREAD

**Issue by bagder** [NEAT-project/neat#371]
The [CMakeLists.txt file](https://github.com/NEAT-project/neat/blob/master/CMakeLists.txt#L309-L310) sets a bunch of compiler options without checking if the used compiler supports them.

This causes warnings and errors when using other/older compilers.

The script should check that the options actually are supported by the used compiler before activating them, or at worst, only add them if asked for by a specific option.

**Comment by weinrank** [comment]
Fixed by #394
