### ISSUE TITLE
NEAT Socket API does NOT support socketpair()

### ISSUE THREAD

**Issue by robustness** [NEAT-project/neat#378]
NEAT socket API is lack the support of socketpair() call, which creates an unnamed pair of connected sockets in the specified domain, of the specified type, and using the optionally specified protocol. 

See the socketpair() description here: 
http://man7.org/linux/man-pages/man2/socketpair.2.html

The socketpair() is used in rsync utility which is supposed to adapt to support NEAT library.

**Comment by dreibh** [comment]
Confirmed. I will add a wrapper.

**Comment by dreibh** [comment]
The wrapper is added in this pull request: https://github.com/NEAT-project/neat/pull/384 .
