### ISSUE TITLE
nsa_pipe() causes "Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by robustness** [NEAT-project/neat#380]
Please just copy and paste the following lines of code and save as hello.c. Then compile and run the code: 
$ gcc -Wall -lneat-socketapi-static  hello.c -o hello
$ ./hello

#include <stdio.h>
#include <neat.h>
#include <neat-socketapi.h>
#include <neat_queue.h>
int main()
{
	int fd[2];
	int ret;
	ret = nsa_pipe(fd);
	if (ret == 0) {
		printf("Sucessfully nsa_pipe\n");
	} else {
		printf("nsa_pipe failed!\n");
	}
	return 0;
}

**Comment by dreibh** [comment]
Could you try the "neat-socketapi" branch? It should fix this issue.

(Note: you just need to include neat-socketapi.h. neat.h and neat_queue.h are not needed for the sockets API.)

**Comment by dreibh** [comment]
Pull request #383 fixes the issue.
