### ISSUE TITLE
Cannot compile socket-api on MacOS

### ISSUE THREAD

**Issue by bozakov** [NEAT-project/neat#404]
The compiler complains about 

    unknown type name 'off64_t

It appear that this can be fixed by including the following in the neat-socketapi header

```
#ifdef __APPLE__
#  define off64_t off_t
#  define fopen64 fopen
#endif
```

However there are also the following errors:

    use of undeclared identifier 'SOCK_NONBLOCK'
    use of undeclared identifier 'SOCK_CLOEXEC'

**Comment by adventureloop** [comment]
A quick search indicates those constants are part of the linux epoll api. I suggest the solution is for @dreibh to document the platforms supported by the socket-api.
