### ISSUE TITLE
MPTCP transport property problem

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#407]
NEAT seems to ignore a property to prefer TCP over MPTCP when running on an MPTCP-capable kernel. MPTCP is enabled by sysctl. NEAT does not turn it off explicitly for the socket:

static const char* properties = "{\
   \"transport\": {\
      \"value\": [ \"TCP\", \"MPTCP\", \"SCTP/UDP\", \"SCTP\" ],\
      \"precedence\": 1\
   }\
}";

This results in the connection to use MPTCP instead of TCP.

**Comment by bozakov** [comment]
I'll take care of this during the Hackathon

**Comment by perhurt** [comment]
Thanks @bozakov 
If you need any assistance, just contact me!

**Comment by bozakov** [comment]
I realized that I misread the question: the order of the value array does not imply a ranking of the individual transports. If you would like to explicitly disable MPTCP whenever TCP is specified, you can define a policy which sets the corresponding MPTCP socket option.
