### ISSUE TITLE
Segmentation fault when testing with tneat in FreeBSD

### ISSUE THREAD

**Issue by fredhau** [NEAT-project/neat#430]
When running the following in FreeBSD:

`$ ./tneat`

and connecting to this server with:

`$ ./tneat <IP address>`

The server terminates with a segmentation fault in `neat_set_operations`. The `opCB` structure passed to `on_connected` contains NULL pointers to `ctx` and `flow` which causes the problem.

This was tested with FreeBSD 11.1-RELEASE r321309

**Comment by weinrank** [comment]
Hey Fredrik,
can you provide a verbose log and a backtrace?
I've tried the scenario and haven't faced any problems.

Greetings
Felix

**Comment by fredhau** [comment]
It seems to work alright now.. I don't really know why it didn't work before. The code was up to date and linked to the NEAT library. However, a `sudo ldconfig` and rebuilding seems to have fixed this.
