### ISSUE TITLE
Assertion failure in io_readable: Assertion 'multistream_flow' failed

### ISSUE THREAD

**Issue by fredhau** [NEAT-project/neat#431]
When running a custom NEAT client on Linux and a custom NEAT server on FreeBSD, I get the following assertion error in the NEAT client:

`neat_core.c:1738: io_readable: Assertion 'multistream_flow' failed.`

However, this error is not present when both of the machines run Linux.

The problem occurs because the code expects `nt_sctp_get_flow_by_sid` to return a multistream flow, but `NULL` is indeed returned.

The following properties are specified at both sides: `{ "transport": { "value": [SCTP], "precedence": 1 } }`. The client sends a HTTP request to the server after connecting, but the problem seems to be related to the reception of the HTTP response from the server.

The Linux system runs Ubuntu 16.04.1 LTS 4.13.0-32-generic. The FreeBSD system runs FreeBSD 11.1-RELEASE r321309.

**Comment by weinrank** [comment]
You're using the latest master branch?

**Comment by fredhau** [comment]
Yes.

**Comment by fredhau** [comment]
Note that this issue still occurs even when SCTP works properly as described in #432. I also tested this on real hardware.

**Comment by weinrank** [comment]
I will check the issue and report back, thanks for the hint.
