### ISSUE TITLE
Can't use IP-Address for neat_open()

### ISSUE THREAD

**Issue by weinrank** [NEAT-project/neat#45]
I created an new example (neat_http_get) to demonstrate the issue:
When using an IP-Address or an unresolvable address `neat_open()` doesn't behave very well. ;)

See buildbots for details.

Steps to reproduce the issue
```
$ neat_http_get bsd10.nplab.de
$ neat_http_get 212.201.121.100
$ neat_http_get not.resolvable.neat
```

**Comment by kristrev** [comment]
Which component is it that fails? Michael and me added support for literals to the resolver some time ago, which seems to work fine. And the resolver should time out with a bogus domain. Of course, we might have missed something ...

**Comment by weinrank** [comment]
I'm currently adding debug output and logging to various functions. When i'm done we hopefully have a clearer view on the issue.
