### ISSUE TITLE
client sample - on_writable callback set at runtime never fired

### ISSUE THREAD

**Issue by weinrank** [NEAT-project/neat#46]
I'm not shure if this is an issue with neat or my example:

In [client.c](https://github.com/NEAT-project/neat/blob/master/samples/client.c#L173) the `tty_read` callback sets the `on_writable` callback [here](https://github.com/NEAT-project/neat/blob/master/samples/client.c#L194)

So the input from stdin, memcopied to the buffer, should be sent via the `on_writable` cb.

This worked fine until the commit ffe037e4b15e39bfb88fddb65db9d6855644d5cc

**Reproduce - success**
```
$ git checkout 2d6162873bb0d86bfffc5af1c06f2f67b0f316dc
cmake and make ...
$ client bsd10.nplab.de 80
type "GET /" and return
The HTML src should be shown instantly
````

**Reproduce - failure**
```
$ git checkout ffe037e4b15e39bfb88fddb65db9d6855644d5cc
cmake and make ...
$ client bsd10.nplab.de 80
type "GET /" and return
The program will idle until the (web)server responds with an 408 Timeout 
````

**Comment by karlgrin** [comment]
Ok. I will check this once I am back coding.

**Comment by kristrev** [comment]
Perhaps we should revert all the HE commits, if those are the ones causing
problems (until bug is fixed)? Now that the project + github has present at
IETF, it will look bad if someone decides to take a look and stuff does not
work.

-Kristian

**Comment by apetlund** [comment]
+1. It's bad timing for broken functionality.

-Andreas

**Comment by tuexen** [comment]
> On 06 Apr 2016, at 08:00, Andreas Petlund <notifications@github.com> wrote:
> 
> +1. It's bad timing for broken functionality.
If we won't have it in the tree, we won't see the issues.
So I think the point is not to have bugs, but fix them. We are giving
access to the development tree, we have not made a release saying this
is working und these conditions.

Making a release and saying this works and it doesn't is a different story.

Best regards
Michael
> 
> -Andreas
>

**Comment by tuexen** [comment]
... I double checked my statement, that we have not done a release by looking at
https://github.com/NEAT-project/neat/releases
and found that we had two releases (v1.0 and v2.0).

I DELETED THESE RELEASES!

I don't think we have agreed on that nor do I think we are
are that stage yet, especially not for a 2.0 version.

Best regards
Michael

**Comment by apetlund** [comment]
:) - unexpected. Thank's for checking.

-AP

**Comment by mcmanus** [comment]
On Apr 6, 2016 9:06 AM, "Michael Tüxen" <notifications@github.com> wrote:
>
> ... I double checked my statement, that we have not done a release by
looking at
> https://github.com/NEAT-project/neat/releases
> and found that we had two releases (v1.0 and v2.0).
>
> I DELETED THESE RELEASES!

Thank you. I agree the right thing is just to work on a .1 with the bug
tracker.. Being open just means transparency about making the sausage.
Actually seeing normal activity including backouts is a sign of health.

Otoh if the state of the tree is blocking other devs then reverting is a
good policy. I'm neutral on that call for this one as I'm busy in ba anyhow
ATM.

>
> I don't think we have agreed on that nor do I think we are
> are that stage yet, especially not for a 2.0 version.
>
> Best regards
> Michael
>
> > On 06 Apr 2016, at 08:00, Andreas Petlund <notifications@github.com>
wrote:
> >
> > +1. It's bad timing for broken functionality.
> >
> > -Andreas
> >
> > On 6 April 2016 at 12:28, Kristian Evensen <notifications@github.com>
wrote:
> >
> > > Perhaps we should revert all the HE commits, if those are the ones
causing
> > > problems (until bug is fixed)? Now that the project + github has
present at
> > > IETF, it will look bad if someone decides to take a look and stuff
does not
> > > work.
> > >
> > > -Kristian
> > >
> > > On Wed, Apr 6, 2016 at 7:59 AM, Karl-Johan Grinnemo <
> > > notifications@github.com> wrote:
> > >
> > > > Ok. I will check this once I am back coding.
> > > >
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly or view it on GitHub
> > > > <
https://github.com/NEAT-project/neat/issues/46#issuecomment-206130594>

**Comment by tuexen** [comment]
> On 06 Apr 2016, at 09:22, Patrick McManus <notifications@github.com> wrote:
> 
> On Apr 6, 2016 9:06 AM, "Michael Tüxen" <notifications@github.com> wrote:
> >
> > ... I double checked my statement, that we have not done a release by
> looking at
> > https://github.com/NEAT-project/neat/releases
> > and found that we had two releases (v1.0 and v2.0).
> >
> > I DELETED THESE RELEASES!
> 
> Thank you. I agree the right thing is just to work on a .1 with the bug
> tracker.. Being open just means transparency about making the sausage.
> Actually seeing normal activity including backouts is a sign of health.
> 
> Otoh if the state of the tree is blocking other devs then reverting is a
> good policy. I'm neutral on that call for this one as I'm busy in ba anyhow
> ATM.
I don't think this is blocking anyone. It gets an initial implementation
in place which now more people can play with, report issues on such that
it can be improved. So far I see no issue with that. No need to back-out
the code as far as I'm concerned.

Best regards
Michael
> 
> >
> > I don't think we have agreed on that nor do I think we are
> > are that stage yet, especially not for a 2.0 version.
> >
> > Best regards
> > Michael
> >
> > > On 06 Apr 2016, at 08:00, Andreas Petlund <notifications@github.com>
> wrote:
> > >
> > > +1. It's bad timing for broken functionality.
> > >
> > > -Andreas
> > >
> > > On 6 April 2016 at 12:28, Kristian Evensen <notifications@github.com>
> wrote:
> > >
> > > > Perhaps we should revert all the HE commits, if those are the ones
> causing
> > > > problems (until bug is fixed)? Now that the project + github has
> present at
> > > > IETF, it will look bad if someone decides to take a look and stuff
> does not
> > > > work.
> > > >
> > > > -Kristian
> > > >
> > > > On Wed, Apr 6, 2016 at 7:59 AM, Karl-Johan Grinnemo <

**Comment by mwelzl** [comment]
> On 6. apr. 2016, at 10.08, Michael Tüxen <notifications@github.com> wrote:
> 
> > On 06 Apr 2016, at 09:22, Patrick McManus <notifications@github.com> wrote:
> > 
> > On Apr 6, 2016 9:06 AM, "Michael Tüxen" <notifications@github.com> wrote:
> > >
> > > ... I double checked my statement, that we have not done a release by
> > looking at
> > > https://github.com/NEAT-project/neat/releases
> > > and found that we had two releases (v1.0 and v2.0).
> > >
> > > I DELETED THESE RELEASES!
> > 
> > Thank you. I agree the right thing is just to work on a .1 with the bug
> > tracker.. Being open just means transparency about making the sausage.
> > Actually seeing normal activity including backouts is a sign of health.
> > 
> > Otoh if the state of the tree is blocking other devs then reverting is a
> > good policy. I'm neutral on that call for this one as I'm busy in ba anyhow
> > ATM.
> I don't think this is blocking anyone. It gets an initial implementation
> in place which now more people can play with, report issues on such that
> it can be improved. So far I see no issue with that. No need to back-out
> the code as far as I'm concerned.

+1

and thanks, Michael, for deleting the releases. I’m sure this was only done by accident.

Cheers,
Michael
