### ISSUE TITLE
Description needed for samples

### ISSUE THREAD

**Issue by naeemk** [NEAT-project/neat#78]
Currently empty `samples/README.md`. We have several tests in `samples/` that need description. Update for the existing samples and also as new items are added.

**Comment by weinrank** [comment]
I will update the readme file within this week. 
Currently there is a mixture of sample and tests in the folder - e.g. the `neat_basic`, `neat_basic_sctp` and `neat_resolver_example` are tests for the NEAT-API in my point of view.

Any objections if i rename the files? `neat_basic` -> `test_basic` or `neat_resolver_example` -> `test_resolver` would make the purpose of the files more clear.

**Comment by naeemk** [comment]
No objection from my side.

**Comment by tuexen** [comment]
> On 10 May 2016, at 09:35, Felix Weinrank <notifications@github.com> wrote:
> 
> I will update the readme file within this week. 
> Currently there is a mixture of sample and tests in the folder - e.g. the neat_basic, neat_basic_sctp and neat_resolver_example are tests for the NEAT-API in my point of view.
> 
> Any objections if i rename the files? neat_basic -> test_basic or neat_resolver_example -> test_resolver would make the purpose of the files more clear.
Maybe even have two directories: One for tests and and for samples? Each with its own
Readme, of course...

Best regards
Michael

**Comment by weinrank** [comment]
@tuexen Sounds good, i will prepare a branch...

@kristrev @karlgrin @mcmanus  do you agree?

**Comment by kristrev** [comment]
Yes, fine by me. However, writing the readme sounds like a good task to do by someone who has not worked with the code but need to get into it ... ;)

**Comment by karlgrin** [comment]
I have no objections against it.

**Comment by weinrank** [comment]
See #79 

@kristrev i agree! 👍
