### ISSUE TITLE
JSON library for NEAT logic

### ISSUE THREAD

**Issue by oystedal** [NEAT-project/neat#82]
We eventually need to decide on a library to use for JSON in the NEAT logic. I have had a look at a few options, and my opinion is that [Jansson](https://github.com/akheron/jansson/) is the best candidate.

* It is licensed under an MIT license, which to my knowledge makes it usable in our context.
* Actively developed.
* [Well-documented API](https://jansson.readthedocs.io/en/2.7/apiref.html).
* The code appears to be well-tested.
* It appears to compile for Windows as well. There are instructions on how to do this, but I have not tried this myself yet.
* a printf-like function to construct JSON objects makes it easy to use, see [json_pack](https://jansson.readthedocs.io/en/2.7/apiref.html#building-values).

If anyone has comments, objections, concerns, or would like to suggest a different library, I'm interested in hearing them. This is not an urgent matter, but it would be nice to have this decided.

I have written some example code to test the library for myself, feel free to check it out here: https://gist.github.com/oystedal/26d67253095160471c74b9d41ac4292f. The JSON structures used in this file are for demonstration purposes only.

Øystein

**Comment by apetlund** [comment]
Jansson seems like a good choice to me too. I will need this for the “neatstat” code as the flow statistics needs a dynamic output format.
 
> On 24 May 2016, at 17:27, oystedal <notifications@github.com> wrote:
> 
> We eventually need to decide on a library to use for JSON in the NEAT logic. I have had a look at a few options, and my opinion is that Jansson <https://github.com/akheron/jansson/> is the best candidate.
> 
> It is licensed under an MIT license, which to my knowledge makes it usable in our context.
> Actively developed.
> Well-documented API <https://jansson.readthedocs.io/en/2.7/apiref.html>.
> The code appears to be well-tested.
> It appears to compile for Windows as well. There are instructions on how to do this, but I have not tried this myself yet.
There’s *BSD support (check). http://portsmon.freebsd.org/portoverview.py?category=devel&portname=jansson <http://portsmon.freebsd.org/portoverview.py?category=devel&portname=jansson>
It’s installable on OSX using homebrew (check).

Cheers,
Andreas

**Comment by weinrank** [comment]
@oystedal The choice lgtm!
@apetlund And netbsd is also supported! ;)
