### ISSUE TITLE
IPv6 test fails on NetBSD

### ISSUE THREAD

**Issue by kristahi** [NEAT-project/neat#84]
This may already be known to those of you working on HE, but the NetBSD buildbot went red since last afternoon.

The `client_http_get 2a02:c6a0:2071:6c1a::105 /cgi-bin/he` test is failing, looks like bind() fails on all enumerated addresses. Looks like this test was added yesterday? Don't know if it's a HE or OS config issue.

**Comment by tuexen** [comment]
@weinrank Can you double check that the NetBSD buildbot has a global IPv6 address.

It looks like NetBSD can't use a link local address to talk to a global address...

**Comment by weinrank** [comment]
The netbsd machine had no global ipv6 address. fixed!
