### ISSUE TITLE
Linux buildbot missing netinet/sctp.h

### ISSUE THREAD

**Issue by kristahi** [NEAT-project/neat#86]
The Ubuntu Linux buildbot seems to be missing the netinet/sctp.h header. Maybe it needs the libsctp-dev package?

From buildbot configure log:

    -- Looking for netinet/sctp.h
    -- Looking for netinet/sctp.h - not found

@weinrank could you please investigate this?

**Comment by tuexen** [comment]
Hmm. I think we had a Linux box with the libsctp-dev  installed and another on without. We didn't want to force people to install something they don't need. Not sure if I'm wrong. However, I think we should have both...
@weinrank What do you think?

**Comment by kristahi** [comment]
I think we should require that package for enabling Linux kernel SCTP, since the SCTP API is not really functional without it.

The code in master just happened to work without because it only used the standard sockets API, but we can't really do a quality implementation of the SCTP side of NEAT if we restrict ourselves to that - and I don't think it makes any sense, either.

This ties in with the whole if-def mess we are wrangling in #85, too. Right now, if you compile on a machine that has kernel SCTP, but misses the headers, you get a broken `io_readable` implementation that reads forever because the updated code requires event handling from the SCTP API.

**Comment by weinrank** [comment]
@kristahi fixed by adding libsctp-dev on the linux bb.

@tuexen mh... i will think about it...

**Comment by tuexen** [comment]
Since the patch is very large, it is hard to get everything by going through it. What do you need from the SCTP API to implement `io_readable`?
@weinrank Maybe we as a group make a decision whether we require the `libsctp-dev` package for `neat` or not. I do understand that it simplifies a lot.
@kristrev Any opinion?

**Comment by weinrank** [comment]
Mh, if i understand kristahi correctly, the `libsctp-dev` is required or at least highly recommended for SCTP on linux.

If that's the case we shouldn't require `libsctp-dev` as mandatory in general but as a requirement for SCTP support.
When the `libsctp-dev`is installed we'll offer native sctp - otherwise not.

**Comment by tuexen** [comment]
Correct, for working SCTP you need `libsctp-dev`. The question is if you should require it also for people not wanting to use SCTP.
I would at least say that the features requiring `libsctp-dev` wouldn't work. Not sure about it in general. Up to now, I used the "rule" to compile what is possible to compile on each platform. HE will figure out if it works. We could also fail user requests at runtime if the support is not compiled in. It depends on what we provide at the API level.

**Comment by weinrank** [comment]
> The question is if you should require it also for people not wanting to use SCTP.

In my opinion the answer is **no**.

> Up to now, I used the "rule" to compile what is possible to compile on each platform.

👍 This should be our general guideline!

**Comment by kristahi** [comment]
> Correct, for working SCTP you need libsctp-dev. The question is if you should require it also for people not wanting to use SCTP.

Note that for end-users installing NEAT as a dependency, the requirement is libsctp itself (Debian package `libsctp1`). It is a dependency for `openjdk-7-jre-headless`, by the way, so anyone with a JRE installed is going to have it.

I agree that it makes no sense to require libsctp if you don't want to support kernel SCTP.

However, I think it is pointless to compile SCTP parts that work without libsctp even if it's not there - the resulting code is not fully functional.

> What do you need from the SCTP API to implement io_readable?

We need the SCTP events API for implementing several of the callbacks. Also, I haven't checked if it actually works to use SCTP at all without having libsctp (just the binaries) installed. Anyone know?

My proposal is to set out these requirements (on Linux):
no SCTP: no additional reqs.
userspace SCTP: no additional reqs.
kernel SCTP: libsctp1 at runtime, libsctp-dev at compile time.

I.e. if libsctp-dev or usrsctp is missing _at compile time_, we don't compile any SCTP support. It would be possible to dynamically load libsctp in order to allow the same binary to work on systems with and without that library, though.

**Comment by tuexen** [comment]
I would say that a user registering a callback requiring a notification, which is not there are compile, should get returned an error. That's all. But I don't see for plain SCTP based communication the need of notifications.
Please note that this changes when OpenSSL comes into the game. But this is handled inside OpenSSL.

One reason to compile in as much as possible us that we depend on functionality being available as compared to predict what is available on a platform. This might change over time. Deprecated API elements might go away, non-deprecated ones might become implemented. Therefore we should not rely on having `sctp_recvmsg()` available. Just prefer `sctp_recvv()` or use the generic `recvmsg`.
I don't see why we need notifications for basic SCTP functionality (except for SENDER_DRY for DTLS). Can you elaborate on what basic functionality doesn't work without notifications? As far as I understand the code the current examples work for SCTP but don't use any notifications, since they where not available...

**Comment by kristahi** [comment]
I looked at the source code of libsctp, and we don't actually need any of the library functions - only the header file.

So I think it makes sense now to say that: libsctp-dev should be a requirement for compiling. libsctp is _not required_ at runtime. Is this okay with everyone?

This is really just a weird artefact of Linux packaging choices.

**Comment by weinrank** [comment]
> libsctp-dev should be a requirement for compiling

Let's clarify what "requirement" means:
Do you mean it should be a mandatory requirement for neat at compile/configure time or a requirement to use sctp within neat?

**Comment by kristahi** [comment]
On June 6, 2016 1:59:18 PM CEST, Felix Weinrank <notifications@github.com> wrote:
>> libsctp-dev should be a requirement for compiling
>
>Let's clarify what "requirement" means:
>Do you mean it should be a mandatory requirement for neat at
>compile/configure time or a requirement to use sctp within neat?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NEAT-project/neat/issues/86#issuecomment-223938791

I mean it should be a requirement for compiling neat with Linux kernel sctp support.

If neither netinet/sctp.h nor usrsctp.h is present (and enabled), Sctp is not compiled.
-- 
Hilsen Kristian

**Comment by tuexen** [comment]
I'm not a linux expert, but once we want to support multihoming on the local side, don't we want to use `sctp_bindx()`? Where is that defined on Linux? I was assuming that it is in the library? What about `sctp_get[lp]addrs()` and `sctp_free[lp]addrs()`? Are they defined in libc?

**Comment by kristahi** [comment]
> I'm not a linux expert, but once we want to support multihoming on the local side, don't we want to use sctp_bindx()? Where is that defined on Linux? I was assuming that it is in the library? What about sctp_get[lp]addrs() and sctp_free[lp]addrs()? Are they defined in libc?

You're right, these are in libsctp and not libc. Hadn't looked at those features yet to be honest.

We could still make it optional to have libsctp at runtime, should be possible to do an implementation with multistreaming and notifications etc without requiring it.


Any objections to requiring one of either netinet/sctp.h (i.e. libsctp-dev) or usrsctp.h to be present at compile time for including Linux SCTP support?

**Comment by tuexen** [comment]
On a system with an SCTP implementation in the kernel, you can really use a userland stack. On Linux, it is fine until the kernel module is loaded. Then you could only do native SCTP in the kernel and UDP encapsulation in userland. Also, this works only as long as Linux does not provide UDP encaps with the kernel implementation.But this mixed implementation (coexistence of a userland and kernelland stack) is not tested and shouldn't be high on the agenda, I think. So I would vote for at most one stack at a time.
What about:
1. If the user has explicitly chosen in the cmake configuration to use usrsctp, do so.
2. If the user has not chosen explicitly usrsctp, use the kernel stuff if available.
I'm don't think this complicates things. We should just have one concept we follow. We can change that in the future. Only avoid a mixture.
What do you gain by requiring exactly one? Happy eyeballs should sort out quickly non-working local candidates.

**Comment by kristahi** [comment]
On June 6, 2016 9:29:27 PM CEST, "Michael Tüxen" <notifications@github.com> wrote:
>On a system with an SCTP implementation in the kernel, you can really
>use a userland stack. On Linux, it is fine until the kernel module is
>loaded. Then you could only do native SCTP in the kernel and UDP
>encapsulation in userland. Also, this works only as long as Linux does
>not provide UDP encaps with the kernel implementation.But this mixed
>implementation (coexistence of a userland and kernelland stack) is not
>tested and shouldn't be high on the agenda, I think. So I would vote
>for at most one stack at a time.
>What about:
>1. If the user has explicitly chosen in the cmake configuration to use
>usrsctp, do so.
>2. If the user has not chosen explicitly usrsctp, use the kernel stuff
>if available.
>I'm don't think this complicates things. We should just have one
>concept we follow. We can change that in the future. Only avoid a
>mixture.
>What do you gain by requiring exactly one? Happy eyeballs should sort
>out quickly non-working local candidates.
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NEAT-project/neat/issues/86#issuecomment-224062400

Agreed re: no mixing of stacks.

I worded myself in negatives, I just meant that if usrsctp is not chosen, then we require the netinet/sctp.h header to be present when compiling sctp support. Otherwise, the binary will have no sctp capability, regardless of what is available at runtime.
-- 
Hilsen Kristian

**Comment by tuexen** [comment]
OK. no mixtures. That is great.
I think the support for usrsctp is now an explicit choice when running cmake. The detection of the availability of netinet/sctp.h is automatic. Do you want to change that?
If neither usrsctp support is compiled in, nor netinet/sctp.h is available at compile time, you could still do basic SCTP communication, can't you? Just compile what you can compile and you should be able to do TCP like services. Or am I missing something?

**Comment by kristahi** [comment]
> The detection of the availability of netinet/sctp.h is automatic. Do you want to change that?

I wanted to change the reaction to not detecting it, by not compiling in any SCTP bits.

> If neither usrsctp support is compiled in, nor netinet/sctp.h is available at compile time, you could still do basic SCTP communication, can't you? Just compile what you can compile and you should be able to do TCP like services.

Yes, that is possible. Made some adjustments to the PR now so this happens without causing any hangs.

**Comment by tuexen** [comment]
OK. I think this improves the code... So can we stick to the "compile as much as possible" principle for now?

**Comment by kristahi** [comment]
Guess we will :)
