### ISSUE TITLE
Handling optional arguments in the API

### ISSUE THREAD

**Issue by kristahi** [NEAT-project/neat#89]
Some of our public API primitives take a large number of optional arguments, e.g. WRITE (6 optional args) and INIT_FLOW (9 optional args!). Therefore, we should decide on some suitable way to handle passing those in.

Specifying all arguments and requiring users to always set them to NULL / zero, etc. doesn't appeal so much to me due to the large number of arguments we are talking about here. The approach we initially went with working on the NEAT Logic BB was to specify "basic" and "extended" versions of these primitives, where only the extended ones had all the extra arguments. That was not very elegant either, does anyone have suggestions or ideas?

(we backed out those primitives from #85, just to be clear)

**Comment by tuexen** [comment]
A suggestion: A TLV based block of memory?

**Comment by kristahi** [comment]
> A suggestion: A TLV structured block of memory?

Sounds like a reasonable way of doing it to me. Should be possible to write some macros to make it easy for programmers to add them, too, I think.

**Comment by evyncke** [comment]
While I agree that this is better to pass a complex/structured object rather than 5+ arguments, TLV looks so ASN.1 BER to me...

While perhaps less efficient, JSON sounds more attractive than TLV.

**Comment by oystedal** [comment]
I'm personally not in favor of any approach that circumvents the little static checking there is in C. 

One approach used in some APIs is to use a pointer to a struct for optional arguments. The struct is allocated and memset with 0's to indicate default values. Alternatively we could have a function initialize the struct with the default values. If no optional arguments are required, one may simply pass `NULL` instead of a pointer to a struct.

**Comment by tuexen** [comment]
I think we will need to provide different structs. We can go than route, but need an additional argument indicating which struct is provided. Something like `setsockopt()`/`getsockopt()`.

**Comment by oystedal** [comment]
I'm not sure why we would need to have more than one struct type passed to each function. My suggestion is to have one struct for each function, such as e.g. `struct neat_open_options` as the last argument to `neat_open`. This struct can of course contain pointers to other structs in addition to values. Example usage would be as follows:

``` C
struct neat_open_options opts;

memset(&opts, 0, sizeof(opts));
// or, if using a function to initialize instead:
neat_open_default_options(&opts);

// Example options
opts.foo = 3;
opts.bar = 1;

neat_open(ctx, flow, name, port, &opts);
// or, if default settings are used:
neat_open(ctx, flow, name, port, NULL);
```

On a different note, how does these options differ from the ones that will eventually be specified with `neat_set_property()`? If there is little to no difference, it might be an idea to reduce the number of settings that can be specified by other means than `neat_set_property()` to keep the entire API as consistent as possible.

**Comment by kristahi** [comment]
Would be good if we could reach concensus here.

IMHO I think JSON is the least desirable option. It just doesn't make good sense to me to use a parsed string format to pass arguments in a C API. This requires users of the library to construct strings, and we have to parse it, potentially for each and every read/write call. You also forgo any help you'd get from the compiler in type checking, etc.

I don't have very strong opinions re: the other two suggestions, although I think the TLV way will allow us to do it "cleaner" - no passing of structs with tons of unused fields. If implemented right, it should be possible to get some type checking and so on, too.

**Comment by oystedal** [comment]
I think a set of TLVs is the way to go.

**Comment by oystedal** [comment]
I have written a suggestion for an implementation for optional arguments using TLVs: https://gist.github.com/oystedal/e8870788690e634df92ec4554a846d2e

It's not a true TLV, in the sense that this implementation in reality just stores pointers to values that are present on the stack. If this approach is deemed acceptable, I plan on changing the `length` member of `struct tlv` to an enum value instead of basing in on the value returned by sizeof, since it may be equal for multiple types.

**Comment by bozakov** [comment]
Wouldn't JSON be easier for application developers, whose life we're trying to make easier with NEAT? Also my expectation was that in the future there may be other implementations of NEAT (Java, Python, etc.) so is a traditional C style API the right way to go for NEAT?

**Comment by kristahi** [comment]
> Wouldn't JSON be easier for application developers, whose life we're trying to make easier with NEAT? 

Is it really easier to (programatically) construct JSON strings in C?

> Also my expectation was that in the future there may be other implementations of NEAT (Java, Python, etc.) so is a traditional C style API the right way to go for NEAT?

I imagine that fitting the API to the appropriate style for those other languages would be accomplished when writing the bindings for those languages. E.g., for Python you'd probably just use the standard optional keyword arguments.

**Comment by mangis-emc** [comment]
This discussion should be addressed in Oslo next week, not inside a github issue, as we agreed on #81 . We will try our best to setup a productive policy/JSON/API session.

**Comment by oystedal** [comment]
In my mind this was/is a different issue than #81. But yes, I think it is a reasonable thing to discuss during the plenary in either case.
