### ISSUE TITLE
Segfault on connect when running examples/server_echo (Linux)

### ISSUE THREAD

**Issue by apetlund** [NEAT-project/neat#91]
When running server_echo with no options and connecting with client (./client localhost 8080) I get a segfault. The last function with a debug printout is neat_set_operations.

Debug tracve
./server_echo
[...] 
[7.126746][DBG] uvpollable_cb
[7.126774][DBG] do_accept
[7.126781][DBG] neat_new_flow
[7.126789][DBG] neat_accept_via_kernel
[7.126810][DBG] io_connected
[7.126817][INF] Connected: TCP/IPv4
peer connected
[7.126831][DBG] neat_set_operations
Segmentation fault (core dumped)

**Comment by oystedal** [comment]
I'm not sure if connecting to `localhost` is supported. For me, when running the two programs as specified above, no connection is made to the server, and the client log contains:
```
[0.123396][ERR] neat_getaddrinfo - No available src addresses
```

Connecting with 127.0.0.1 works as expected.

Further information such as what system/kernel you are testing on would be helpful. I also suggest running the server using `valgrind` to track down the segfault. Post the output from valgrind here.

**Comment by apetlund** [comment]
Ok. It used to work until one of the last commits to the master branch.

I’ll use 127.0.0.1 for my testing in the meantime. You decide whether this is bug or feature :)

-Andreas

**Comment by weinrank** [comment]
I tried to reproduce the issue but for me it works fine.
Tested with Ubuntu 16.04 and latest master revision b6e436e

I attached my cmake,build,echo_server and client logfiles.

[build.txt](https://github.com/NEAT-project/neat/files/316495/build.txt)
[client.txt](https://github.com/NEAT-project/neat/files/316493/client.txt)
[cmake.txt](https://github.com/NEAT-project/neat/files/316494/cmake.txt)
[server.txt](https://github.com/NEAT-project/neat/files/316496/server.txt)

Do you have usrsctp/sctp kernel support installed?

**Comment by apetlund** [comment]
I got home and tested it on another workstation and here it worked fine. I'll try to descipher the difference between my two environments myself. Closing the issue.

**Comment by apetlund** [comment]
After cleaning up all object files in the build folders, the problem went away. Seems there may have been some error in the Make setup when switching between branches. I'm ignoring it for now.
