### ISSUE TITLE
Suggested coding style

### ISSUE THREAD

**Issue by oystedal** [NEAT-project/neat#94]
I have created a suggestion for a coding style for the project, something which has been previously requested.

[Here is a set of slides presenting the suggested code style.](https://docs.google.com/presentation/d/10yYbafjmgp4kUlExhE6zjUXOWsfR2wP3198r3_eOOE8/edit?usp=sharing)

I suggest we keep the discussion here on GitHub.

The majority of the style is based on the code that is already present. Some points are, inevitably, based on my own opinion. I have tried to justify these, but this is often a matter of personal preference. In the end, I think it is more important to have a well-defined style that is followed consistently than what the exact details of the style is.

Ultimately, a configuration file for some code formatting tool, most likely [Uncrustify](https://github.com/uncrustify/uncrustify), will be provided to alleviate the task of checking and formatting the code.

As always, we are open to comments, criticism, and suggestions.

**Comment by weinrank** [comment]
The sooner the better!

If you provide the crustify config file in the repo, i will add a buildbot step for it.
