### ISSUE TITLE
Policy Manager outputs invalid JSON

### ISSUE THREAD

**Issue by kristahi** [NEAT-project/neat#96]
It appears proper, standards-compliant JSON cannot encode NaN values. These are used rather a lot by the PM, and end up in the resulting JSON for interfacing with NEAT Logic.

The libjansson library we use for parsing JSON in C doesn't give any options to pretend NaN are OK, so we must work around this issue somehow.
I patched neatpmd.py as so:
`    api_writer(candidates_json.replace('NaN', '"NaN"'))` as a temporary workaround.

**Comment by evyncke** [comment]
What about replacing 'NaN' by a simple 'null' ?

**Comment by oystedal** [comment]
I think we should distinguish between an invalid (NaN) and a missing (null) value.

**Comment by kristrev** [comment]
Why even bother including invalid or missing values? What is the advantage of exporting them from the PM? Invalid sounds like it should be considered an error in the PM, while missing can be infered from key missing.

**Comment by kristahi** [comment]
AFAIK the NaN values are used to indicate properties the PM couldn't generate a meaningful score for.

Possible solutions could be to put a string or boolean (i.e., value of `false`) there instead in those cases, or introducing another key (`scored: bool` or something).

Ideas @bozakov @mangis-emc ?

**Comment by bozakov** [comment]
The motivation for the missing values is exactly as @kristahi pointed out. Any attribute which the PM didn't have enough information to act upon will not have an assigned score after the PM lookup. This differentiation is important for properties such as, `TLS_required`, which **must** be enforced by the NEAT logic - even in cases where the PM doesn't yet know wether the remote endpoint supports TLS or not.

The 'NaN' value is essentially a placeholder, we can replace it with a string, boolean or use some other explicit notation - I'm open to suggestions. Maybe the simplest approach would be to omit the `score` key if it has not been set - as long as the NEAT logic knows that this implies that this property could not be evaluated during the PM step.
